/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// ---------------------------------------------------------------------------
// WS2 T3.1 Step 3 — es/fr/de/pt conformance guard for `canonicalize()`.
//
// `scripts/fixtures/canonicalize-conformance-fixture.json` is a committed
// snapshot of `canonicalize()`'s output over a curated es/fr/de/pt corpus,
// generated by driving THIS live function directly (never through the sync
// pipeline) via `scripts/generate-canonicalize-conformance-fixture.ts`. No
// existing corpus (v6/173/spanish, the golden replay) exercises the fr/de/pt
// branches at all, and the spanish corpus's own tokenHash column (WS2 T3.1
// Step 4) cannot reach them either — this is the only place that coverage
// lands.
//
// LOCKS CURRENT BEHAVIOR, NOT DESIRED BEHAVIOR. Every entry's `tokens` is
// asserted against canonicalize(input, language) as-is; `knownLossy`/
// `notDetermined` (see the generator) document known gaps without fixing
// them. If this test fails because canonicalize() changed deliberately:
// re-run `npx tsx scripts/generate-canonicalize-conformance-fixture.ts`,
// review the diff for real behavioral change (not just formatting), and
// update `knownLossy`/`notDetermined` notes if the change touches one of
// them — never regenerate the fixture just to silence this test.
//
// Also re-derives (never just trusts) the undefined-equals-'en' identity per
// entry: canonicalize(text, undefined) must equal canonicalize(text, 'en')
// byte-for-byte. That identity is what every pre-language-threading call site
// (which passed no languageCode) implicitly relied on, and until this fixture
// it had only ever been asserted against synthetic unit-test strings, never
// against real es/fr/de/pt prose.
// ---------------------------------------------------------------------------

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { canonicalize } from './textNormalize';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

type Lang = 'es' | 'fr' | 'de' | 'pt';

interface FixtureEntry {
  language: Lang;
  input: string;
  note: string;
  tokens: string[];
  tokensUndefined: string[];
  tokensEn: string[];
  undefinedEqualsEn: boolean;
  knownLossy: string | null;
  notDetermined: string | null;
}

interface FixtureFile {
  entries: FixtureEntry[];
}

const fixture: FixtureFile = JSON.parse(
  readFileSync(resolve(REPO, 'scripts', 'fixtures', 'canonicalize-conformance-fixture.json'), 'utf-8'),
) as FixtureFile;

const LANGUAGES: Lang[] = ['es', 'fr', 'de', 'pt'];

describe('canonicalize-conformance-fixture.json — drift guard against the live canonicalize()', () => {
  it('the fixture is non-empty and covers es/fr/de/pt', () => {
    expect(fixture.entries.length).toBeGreaterThan(0);
    const seen = new Set(fixture.entries.map(e => e.language));
    for (const lang of LANGUAGES) {
      expect(seen.has(lang), `fixture missing coverage for "${lang}"`).toBe(true);
    }
  });

  it('every committed undefinedEqualsEn flag is true (fixture self-consistency)', () => {
    for (const entry of fixture.entries) {
      expect(entry.undefinedEqualsEn, `${entry.language} ${JSON.stringify(entry.input)}`).toBe(true);
    }
  });

  for (const entry of fixture.entries) {
    const label = `${entry.language}: ${JSON.stringify(entry.input)} (${entry.note})`;

    it(`${label} — tokens match the committed fixture`, () => {
      expect(canonicalize(entry.input, entry.language)).toEqual(entry.tokens);
    });

    it(`${label} — undefined ≡ 'en', re-derived against real text`, () => {
      const und = canonicalize(entry.input, undefined);
      const en = canonicalize(entry.input, 'en');
      expect(und).toEqual(en);
      expect(und).toEqual(entry.tokensUndefined);
      expect(en).toEqual(entry.tokensEn);
    });
  }
});
