/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// ---------------------------------------------------------------------------
// WS1 Task 5 Slice D3 — drift guard.
//
// `scripts/fixtures/fa-text-normalize-fixture.json` is a committed snapshot
// of `normalizeForForcedAlignment`'s output, generated by driving THIS live
// module (`scripts/generate-fa-text-fixture.ts`). `src-tauri/src/fa/text.rs`
// asserts its Rust port matches that same fixture byte-for-byte. This test
// closes the loop on the OTHER side: if a future change to
// `faTextNormalize.ts` alters output for any corpus case without the fixture
// being regenerated, this test fails loudly here — rather than the Rust and
// TS implementations silently drifting apart with neither side's test suite
// noticing.
//
// If this test fails because `faTextNormalize.ts` changed deliberately:
// re-run `npx tsx scripts/generate-fa-text-fixture.ts`, review the diff, and
// port the same behavioral change into `src-tauri/src/fa/text.rs` before
// committing — never regenerate the fixture just to silence this test.
// ---------------------------------------------------------------------------

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import {
  normalizeForForcedAlignment,
  vocabCharsFromRawVocab,
  type FaLanguageCode,
  type FaCardinalData,
} from './faTextNormalize';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

interface FixtureWord {
  input: string;
  representable: boolean;
  mapped: string | null;
  reason: string | null;
}

interface FixtureEntry {
  language: FaLanguageCode;
  input: string;
  note: string;
  words: FixtureWord[];
  text: string;
}

interface FixtureFile {
  entries: FixtureEntry[];
}

function loadVocabChars(lang: FaLanguageCode): Set<string> {
  const raw = JSON.parse(
    readFileSync(resolve(REPO, 'scripts', 'fixtures', `fa-vocab-${lang}.json`), 'utf-8'),
  ) as { vocab: Record<string, number> };
  return vocabCharsFromRawVocab(raw.vocab);
}

function loadCardinalData(lang: FaLanguageCode): FaCardinalData {
  return JSON.parse(
    readFileSync(resolve(REPO, 'scripts', 'fixtures', `fa-cardinal-${lang}.json`), 'utf-8'),
  ) as FaCardinalData;
}

const LANGUAGES: FaLanguageCode[] = ['en', 'es', 'fr', 'de', 'pt'];
const VOCABS: Record<FaLanguageCode, Set<string>> = Object.fromEntries(
  LANGUAGES.map(lang => [lang, loadVocabChars(lang)]),
) as Record<FaLanguageCode, Set<string>>;
const CARDINAL_DATA: Record<FaLanguageCode, FaCardinalData> = Object.fromEntries(
  LANGUAGES.map(lang => [lang, loadCardinalData(lang)]),
) as Record<FaLanguageCode, FaCardinalData>;

const fixture: FixtureFile = JSON.parse(
  readFileSync(resolve(REPO, 'scripts', 'fixtures', 'fa-text-normalize-fixture.json'), 'utf-8'),
) as FixtureFile;

describe('fa-text-normalize-fixture.json — drift guard against the live TS module', () => {
  it('the fixture is non-empty and covers all five languages', () => {
    expect(fixture.entries.length).toBeGreaterThan(0);
    const seen = new Set(fixture.entries.map(e => e.language));
    for (const lang of LANGUAGES) {
      expect(seen.has(lang), `fixture missing coverage for "${lang}"`).toBe(true);
    }
  });

  for (const entry of fixture.entries) {
    it(`${entry.language}: ${JSON.stringify(entry.input)} (${entry.note}) matches the committed fixture`, () => {
      const result = normalizeForForcedAlignment(entry.input, entry.language, VOCABS[entry.language], CARDINAL_DATA[entry.language]);

      expect(result.text).toBe(entry.text);
      expect(result.words).toHaveLength(entry.words.length);
      result.words.forEach((word, i) => {
        const want = entry.words[i]!;
        expect(word.input).toBe(want.input);
        expect(word.representable).toBe(want.representable);
        expect(word.mapped ?? null).toBe(want.mapped);
        expect(word.reason ?? null).toBe(want.reason);
      });
    });
  }
});
