// src/services/lookPresetService.ts
// Combined-look effect presets (transition + animation + overlay slugs + durations),
// persisted in a dedicated localStorage store separate from presetService.ts.

export interface LookPreset {
  id: string;
  name: string;
  transition: string;
  transitionDur: number;
  animation: string;
  animationDur: number;
  overlay: string;
}

export const MAX_LOOK_PRESETS = 20;

const LOOK_PRESETS_KEY = 'kinetix:lookPresets:v1';

export function loadLookPresets(): LookPreset[] {
  try {
    const raw = localStorage.getItem(LOOK_PRESETS_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as LookPreset[];
  } catch {
    return [];
  }
}

function saveRaw(presets: LookPreset[]): void {
  try {
    localStorage.setItem(LOOK_PRESETS_KEY, JSON.stringify(presets));
  } catch {
    // ignore storage errors
  }
}

/**
 * Save a look preset, preserving the caller-supplied id (so the id generated by
 * the caller — e.g. EffectsPanel's crypto.randomUUID() — survives the round-trip
 * and stays valid for any local activeId comparisons).
 * Returns null (without saving) if MAX_LOOK_PRESETS is reached.
 * If a preset with the same id already exists, no duplicate row is added —
 * the existing stored record is returned as-is.
 */
export function saveLookPreset(preset: LookPreset): LookPreset | null {
  const existing = loadLookPresets();
  const already = existing.find(p => p.id === preset.id);
  if (already) return already;
  if (existing.length >= MAX_LOOK_PRESETS) return null;
  saveRaw([...existing, preset]);
  return preset;
}

export function deleteLookPreset(id: string): void {
  const existing = loadLookPresets();
  saveRaw(existing.filter(p => p.id !== id));
}
