export {
  EXPORT_FAILURE_COPY,
  FINISH_SHORTFALL_COPY,
  GRAPHICS_CONTEXT_LOST_NOTE,
  HARDWARE_FAILOVER_NOTE,
  NEVER_RESUME_KINDS,
  RESUME_UNAVAILABLE_COPY,
  isNeverResumeKind,
  type ExportFailureCopyMap,
  type ExportFailureKindCopy,
} from './exportFailureCopy';
export {
  destroySessionDestroyedDisposition,
  hardwareNoteFor,
  isResumeEligible,
  resolveExportFailurePresentation,
  retainForResumeDestroyedDisposition,
  retainedForResumeDisposition,
  shouldMentionHardware,
  shouldOfferResume,
  type DiskFullCardVariant,
  type ExportFailurePresentation,
  type ExportFailurePresentationInput,
  type RetentionEvidence,
} from './resumeEligibility';
