// ---------------------------------------------------------------------------
// Forced-alignment vocab-aware text normalizer — Rust port (WS1 Task 5 Slice
// D3) of `src/services/faTextNormalize.ts`. That TS module is the source of
// truth for every rule below; this file is a byte-identical port, proven via
// the shared fixture `scripts/fixtures/fa-text-normalize-fixture.json`
// (generated by `scripts/generate-fa-text-fixture.ts` by driving the *live*
// TS module — never hand-derived) and this file's `fixture_parity` tests.
//
// UNCONDITIONAL — not behind `#[cfg(feature = "fa-inference")]` — so the
// default build (no ML dependency) still compiles and tests this module.
// Replaces `fa_onnx.rs`'s former ASCII-only placeholder tokenizer.
//
// DELIBERATE DEVIATIONS FROM A LITERAL, GENERAL-PURPOSE NFC/`\s` PORT (see
// each site below for detail — both are narrow, safe-by-construction, and
// were confirmed necessary by directly testing V8's actual behavior, not
// assumed from spec text alone):
//
//   1. NFC normalization. `normalizeWord`'s first step is
//      `rawWord.normalize('NFC')`. Rust's std has no Unicode normalization,
//      and this slice's scope caps Cargo dependency changes at the
//      `serde_json` feature-gate promotion (see `Cargo.toml`) — no new crate.
//      `compose_scoped_nfc` below hand-composes exactly the ~54
//      base(+case)/combining-mark pairs that produce the accented letters
//      actually present across the five shipped vocabs (verified by
//      `unicodedata.normalize('NFD', ch)` over the union of every non-ASCII
//      char in `scripts/fixtures/fa-vocab-*.json`, all single-mark — none of
//      the five vocabs contain a canonically-decomposable ligature or a
//      multi-mark precomposed character). A decomposed sequence outside this
//      table simply fails to compose and falls through unchanged — normal
//      per-character vocab-membership rejection then handles it exactly like
//      any other genuinely out-of-vocab character (safe fallback: worst case
//      is an unnecessary "unrepresentable", never a wrong composition).
//
//   2. Whitespace splitting. `normalizeForForcedAlignment` splits on JS's
//      `/\s+/`, whose `\s` class is ECMA-262's WhiteSpace+LineTerminator set
//      — notably INCLUDES U+FEFF (BOM/ZWNBSP) and EXCLUDES U+0085 (NEL).
//      Rust's `char::is_whitespace()` (Unicode White_Space property) is the
//      opposite on both points. Confirmed directly: in Node,
//      `"a﻿b".split(/\s+/)` -> `["a", "b"]` — FEFF splits a word in the
//      reference implementation, so a Rust port using `str::split_whitespace`
//      would silently diverge on that input. `is_js_whitespace` below
//      reproduces the exact ECMA-262 `\s` code point set instead.
// ---------------------------------------------------------------------------

// Compiled in every config (see module doc comment above), but this module's
// only non-test consumer (`fa_onnx.rs`) is itself gated on `fa-inference` —
// so with that feature off, every item here is genuinely unreachable outside
// of this file's own `#[cfg(test)]` modules. Mirrors the same
// `#[cfg_attr(not(feature = "fa-inference"), allow(dead_code))]` convention
// `fa.rs` already uses for its own multi-config items, applied once at the
// module level here since the entire public surface is in the same boat.
#![cfg_attr(not(feature = "fa-inference"), allow(dead_code))]

use std::collections::HashSet;
use std::fmt;
use std::path::Path;

// ---------------------------------------------------------------------------
// Language
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Language {
    En,
    Es,
    Fr,
    De,
    Pt,
}

impl Language {
    pub fn code(self) -> &'static str {
        match self {
            Language::En => "en",
            Language::Es => "es",
            Language::Fr => "fr",
            Language::De => "de",
            Language::Pt => "pt",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "en" => Some(Language::En),
            "es" => Some(Language::Es),
            "fr" => Some(Language::Fr),
            "de" => Some(Language::De),
            "pt" => Some(Language::Pt),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Vocab loading — `vocabCharsFromRawVocab`'s port, plus a path-based loader
// since Rust (unlike the TS caller) has no "already-parsed-JSON-in-hand"
// entry point of its own. Vocab is always loaded from a CALLER-SUPPLIED path
// — this module never embeds, hardcodes, or resolves a vocab path itself
// (never reaches into `src-tauri/models/`).
// ---------------------------------------------------------------------------

/// Vocab-JSON entries that are CTC bookkeeping tokens, not literal spellable
/// characters — `|` is wav2vec2's word-delimiter token, not a printable pipe.
const NON_CHARACTER_VOCAB_TOKENS: &[&str] = &["<pad>", "<s>", "</s>", "<unk>", "|"];

/// Error type for [`vocab_chars_from_path`] — the only non-test-exclusive
/// consumer would be a future caller loading vocab from a real filesystem
/// path; see that function's doc comment for why it's test-only today.
#[cfg_attr(not(test), allow(dead_code))]
#[derive(Debug)]
pub enum TextError {
    Io(String),
    Json(String),
    MissingVocabField,
}

impl fmt::Display for TextError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TextError::Io(msg) => write!(f, "failed to read vocab file: {msg}"),
            TextError::Json(msg) => write!(f, "failed to parse vocab JSON: {msg}"),
            TextError::MissingVocabField => write!(f, "vocab JSON missing a \"vocab\" object field"),
        }
    }
}

impl std::error::Error for TextError {}

/// Derives the set of literal, spellable characters from a model's raw
/// `vocab.json` object (as committed verbatim in `scripts/fixtures/
/// fa-vocab-<lang>.json`'s `vocab` field) — i.e. every key except the CTC
/// special/delimiter tokens above. Mirrors `vocabCharsFromRawVocab`.
pub fn vocab_chars_from_raw_vocab(raw_vocab: &serde_json::Map<String, serde_json::Value>) -> HashSet<char> {
    let mut chars = HashSet::new();
    for key in raw_vocab.keys() {
        if NON_CHARACTER_VOCAB_TOKENS.contains(&key.as_str()) {
            continue;
        }
        if key.chars().count() == 1 {
            chars.insert(key.chars().next().unwrap());
        }
    }
    chars
}

/// Reads and parses a `fa-vocab-<lang>.json`-shaped file at `path` (caller-
/// supplied — this function performs no path resolution of its own) and
/// returns its vocab-membership character set. Used by this crate's own
/// tests to load `scripts/fixtures/fa-vocab-<lang>.json` directly (mirroring
/// `faTextNormalize.test.ts`'s `loadVocabChars`); `fa_onnx.rs`'s production
/// path embeds its vocab JSON via `include_str!` instead (see that file) and
/// so never calls this — hence `allow(dead_code)` outside test builds.
#[cfg_attr(not(test), allow(dead_code))]
pub fn vocab_chars_from_path(path: &Path) -> Result<HashSet<char>, TextError> {
    let contents = std::fs::read_to_string(path).map_err(|e| TextError::Io(e.to_string()))?;
    let parsed: serde_json::Value = serde_json::from_str(&contents).map_err(|e| TextError::Json(e.to_string()))?;
    let vocab_obj = parsed
        .get("vocab")
        .and_then(|v| v.as_object())
        .ok_or(TextError::MissingVocabField)?;
    Ok(vocab_chars_from_raw_vocab(vocab_obj))
}

// ---------------------------------------------------------------------------
// NFC (scoped) — see module doc comment, deviation 1.
// ---------------------------------------------------------------------------

/// (base, combining mark, precomposed) — every base(+case)/mark pair needed
/// to reconstruct the accented letters present across the five shipped
/// vocabs when they arrive NFD-decomposed. Generated from
/// `unicodedata.normalize('NFD', ch)` over each vocab's non-ASCII characters
/// — see module doc comment.
const NFC_COMPOSE: &[(char, char, char)] = &[
    ('a', '\u{0300}', 'à'),
    ('A', '\u{0300}', 'À'),
    ('a', '\u{0301}', 'á'),
    ('A', '\u{0301}', 'Á'),
    ('a', '\u{0302}', 'â'),
    ('A', '\u{0302}', 'Â'),
    ('a', '\u{0308}', 'ä'),
    ('A', '\u{0308}', 'Ä'),
    ('a', '\u{0303}', 'ã'),
    ('A', '\u{0303}', 'Ã'),
    ('c', '\u{0327}', 'ç'),
    ('C', '\u{0327}', 'Ç'),
    ('c', '\u{0301}', 'ć'),
    ('C', '\u{0301}', 'Ć'),
    ('c', '\u{030c}', 'č'),
    ('C', '\u{030c}', 'Č'),
    ('e', '\u{0300}', 'è'),
    ('E', '\u{0300}', 'È'),
    ('e', '\u{0301}', 'é'),
    ('E', '\u{0301}', 'É'),
    ('e', '\u{0302}', 'ê'),
    ('E', '\u{0302}', 'Ê'),
    ('e', '\u{0308}', 'ë'),
    ('E', '\u{0308}', 'Ë'),
    ('i', '\u{0301}', 'í'),
    ('I', '\u{0301}', 'Í'),
    ('i', '\u{0302}', 'î'),
    ('I', '\u{0302}', 'Î'),
    ('i', '\u{0308}', 'ï'),
    ('I', '\u{0308}', 'Ï'),
    ('n', '\u{0303}', 'ñ'),
    ('N', '\u{0303}', 'Ñ'),
    ('o', '\u{0301}', 'ó'),
    ('O', '\u{0301}', 'Ó'),
    ('o', '\u{0302}', 'ô'),
    ('O', '\u{0302}', 'Ô'),
    ('o', '\u{0308}', 'ö'),
    ('O', '\u{0308}', 'Ö'),
    ('o', '\u{0303}', 'õ'),
    ('O', '\u{0303}', 'Õ'),
    ('o', '\u{0304}', 'ō'),
    ('O', '\u{0304}', 'Ō'),
    ('s', '\u{030c}', 'š'),
    ('S', '\u{030c}', 'Š'),
    ('s', '\u{0326}', 'ș'),
    ('S', '\u{0326}', 'Ș'),
    ('u', '\u{0300}', 'ù'),
    ('U', '\u{0300}', 'Ù'),
    ('u', '\u{0301}', 'ú'),
    ('U', '\u{0301}', 'Ú'),
    ('u', '\u{0302}', 'û'),
    ('U', '\u{0302}', 'Û'),
    ('u', '\u{0308}', 'ü'),
    ('U', '\u{0308}', 'Ü'),
];

fn compose_pair(base: char, mark: char) -> Option<char> {
    NFC_COMPOSE.iter().find(|&&(b, m, _)| b == base && m == mark).map(|&(_, _, c)| c)
}

/// Scoped NFC composition — see module doc comment, deviation 1.
fn compose_scoped_nfc(word: &str) -> String {
    let mut out = String::with_capacity(word.len());
    let mut pending: Option<char> = None;
    for ch in word.chars() {
        match pending {
            Some(base) => match compose_pair(base, ch) {
                Some(composed) => pending = Some(composed),
                None => {
                    out.push(base);
                    pending = Some(ch);
                }
            },
            None => pending = Some(ch),
        }
    }
    if let Some(base) = pending {
        out.push(base);
    }
    out
}

// ---------------------------------------------------------------------------
// JS-`\s`-equivalent whitespace splitting — see module doc comment, deviation 2.
// ---------------------------------------------------------------------------

fn is_js_whitespace(ch: char) -> bool {
    matches!(
        ch,
        '\u{0009}'..='\u{000D}'
            | '\u{0020}'
            | '\u{00A0}'
            | '\u{1680}'
            | '\u{2000}'..='\u{200A}'
            | '\u{2028}'
            | '\u{2029}'
            | '\u{202F}'
            | '\u{205F}'
            | '\u{3000}'
            | '\u{FEFF}'
    )
}

/// Mirrors `input.split(/\s+/).filter(w => w.length > 0)`.
fn split_js_whitespace(input: &str) -> Vec<&str> {
    input.split(is_js_whitespace).filter(|w| !w.is_empty()).collect()
}

// ---------------------------------------------------------------------------
// Zero-width stripping, typographic folding, boundary-punctuation stripping
// ---------------------------------------------------------------------------

/// Zero-width/invisible characters — stripped wherever they occur in a token
/// (copy-paste artifacts, not meaningful word content): zero-width space,
/// zero-width non-joiner/joiner, BOM/zero-width no-break space, word joiner.
fn is_zero_width(ch: char) -> bool {
    matches!(ch, '\u{200B}' | '\u{200C}' | '\u{200D}' | '\u{FEFF}' | '\u{2060}')
}

fn strip_zero_width(word: &str) -> String {
    word.chars().filter(|&c| !is_zero_width(c)).collect()
}

/// Typographic variant -> ASCII target. Mirrors `FOLD_TARGETS`.
fn fold_target(ch: char) -> Option<char> {
    match ch {
        '\u{2018}' => Some('\''), // LEFT SINGLE QUOTATION MARK
        '\u{2019}' => Some('\''), // RIGHT SINGLE QUOTATION MARK
        '\u{02BC}' => Some('\''), // MODIFIER LETTER APOSTROPHE
        '\u{2010}' => Some('-'),  // HYPHEN
        '\u{2011}' => Some('-'),  // NON-BREAKING HYPHEN
        '\u{2013}' => Some('-'),  // EN DASH
        '\u{2014}' => Some('-'),  // EM DASH
        '\u{201C}' => Some('"'),  // LEFT DOUBLE QUOTATION MARK
        '\u{201D}' => Some('"'),  // RIGHT DOUBLE QUOTATION MARK
        '\u{201E}' => Some('"'),  // DOUBLE LOW-9 QUOTATION MARK
        '\u{201F}' => Some('"'),  // DOUBLE HIGH-REVERSED-9 QUOTATION MARK
        _ => None,
    }
}

/// Substitutes each typographic variant found anywhere in the token for its
/// ASCII target, but only when the target is actually a member of this
/// language's vocab — otherwise the variant is dropped (strip, not fold).
fn fold_typographic_variants(word: &str, vocab_chars: &HashSet<char>) -> String {
    let mut out = String::with_capacity(word.len());
    for ch in word.chars() {
        match fold_target(ch) {
            None => out.push(ch),
            Some(target) if vocab_chars.contains(&target) => out.push(target),
            Some(_) => {} // fold target absent from vocab — drop the character entirely.
        }
    }
    out
}

/// Word-boundary punctuation: stripped from a token's leading/trailing edges
/// only (never word-internal).
fn is_boundary_punct(ch: char) -> bool {
    matches!(ch, '.' | ',' | ';' | ':' | '?' | '!' | '"' | '«' | '»' | '(' | ')')
}

/// Strips boundary punctuation from a token's leading/trailing edges only,
/// repeatedly, so stacked marks (e.g. a quote-and-comma pair) fully clear.
fn strip_boundary_punctuation(word: &str) -> &str {
    word.trim_matches(is_boundary_punct)
}

// ---------------------------------------------------------------------------
// German ß -> ss
// ---------------------------------------------------------------------------

/// German's vocab has no `ß` — the standard `ß` -> `ss` expansion is applied
/// before the vocab-membership check, not treated as an unrepresentable
/// character. Applied only for `de`; a no-op otherwise.
fn apply_language_specific_substitutions(word: &str, language: Language) -> String {
    if language == Language::De {
        word.replace('ß', "ss")
    } else {
        word.to_string()
    }
}

// ---------------------------------------------------------------------------
// Word / phrase normalization
// ---------------------------------------------------------------------------

/// One normalized word (or the reason it couldn't be). Mirrors `FaWordResult`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WordResult {
    /// The original whitespace-delimited slice, before any mapping.
    pub input: String,
    pub representable: bool,
    /// `Some` iff `representable` — every character here is a vocab member.
    pub mapped: Option<String>,
    /// `Some` iff NOT `representable` — why this word was dropped.
    pub reason: Option<String>,
}

/// Mirrors `FaNormalizeResult`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NormalizeResult {
    /// One entry per whitespace-delimited word in the input, in order.
    pub words: Vec<WordResult>,
    /// Representable words' `mapped` text, single-space-joined.
    pub text: String,
}

/// Normalizes one already-whitespace-isolated word: scoped-NFC + lowercase,
/// the German ß->ss substitution, zero-width stripping, typographic folding,
/// boundary-punctuation stripping, then a digit check and a per-character
/// vocab membership check. Mirrors `normalizeWord`.
pub fn normalize_word(raw_word: &str, language: Language, vocab_chars: &HashSet<char>) -> WordResult {
    let nfc = compose_scoped_nfc(raw_word);
    let lowered = nfc.to_lowercase();
    let substituted = apply_language_specific_substitutions(&lowered, language);
    let dezero_widthed = strip_zero_width(&substituted);
    let folded = fold_typographic_variants(&dezero_widthed, vocab_chars);
    let stripped = strip_boundary_punctuation(&folded);

    if stripped.is_empty() {
        return WordResult {
            input: raw_word.to_string(),
            representable: false,
            mapped: None,
            reason: Some(format!(
                "reduced to nothing by fold/strip — no word content remained (word: \"{raw_word}\")"
            )),
        };
    }

    if stripped.chars().any(|c| c.is_ascii_digit()) {
        return WordResult {
            input: raw_word.to_string(),
            representable: false,
            mapped: None,
            reason: Some(format!(
                "contains a digit — number expansion is Phase 3b, out of scope (word: \"{raw_word}\")"
            )),
        };
    }

    for ch in stripped.chars() {
        if !vocab_chars.contains(&ch) {
            return WordResult {
                input: raw_word.to_string(),
                representable: false,
                mapped: None,
                reason: Some(format!(
                    "character \"{ch}\" is not in the {} vocab (word: \"{raw_word}\")",
                    language.code()
                )),
            };
        }
    }

    WordResult { input: raw_word.to_string(), representable: true, mapped: Some(stripped.to_string()), reason: None }
}

/// Normalizes a word or whitespace-separated phrase against one language's
/// CTC vocab. Mirrors `normalizeForForcedAlignment`.
pub fn normalize_for_forced_alignment(input: &str, language: Language, vocab_chars: &HashSet<char>) -> NormalizeResult {
    let raw_words = split_js_whitespace(input);
    let words: Vec<WordResult> = raw_words.iter().map(|w| normalize_word(w, language, vocab_chars)).collect();
    let text = words
        .iter()
        .filter(|w| w.representable)
        .map(|w| w.mapped.as_deref().unwrap())
        .collect::<Vec<_>>()
        .join(" ");
    NormalizeResult { words, text }
}

// ---------------------------------------------------------------------------
// Unit tests — pipeline mechanics not already covered by fixture parity below
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn vocab(chars: &[char]) -> HashSet<char> {
        chars.iter().copied().collect()
    }

    #[test]
    fn compose_scoped_nfc_recomposes_decomposed_accent() {
        // "e" + COMBINING ACUTE ACCENT -> "é"
        let decomposed = "e\u{0301}";
        assert_eq!(compose_scoped_nfc(decomposed), "é");
    }

    #[test]
    fn compose_scoped_nfc_leaves_already_precomposed_untouched() {
        assert_eq!(compose_scoped_nfc("café"), "café");
    }

    #[test]
    fn compose_scoped_nfc_leaves_unknown_combining_sequence_unchanged() {
        // COMBINING DOT ABOVE on "z" isn't in the scoped table for any
        // shipped vocab — must pass through untouched (safe fallback), not
        // silently merge or vanish.
        let input = "z\u{0307}";
        assert_eq!(compose_scoped_nfc(input), input);
    }

    #[test]
    fn split_js_whitespace_treats_bom_as_a_splitter_like_v8_does() {
        // Confirmed via node: "a﻿b".split(/\s+/) -> ["a", "b"].
        assert_eq!(split_js_whitespace("a\u{FEFF}b"), vec!["a", "b"]);
    }

    #[test]
    fn split_js_whitespace_does_not_split_on_zero_width_space() {
        // U+200B is not in JS's \s class — stays one token, handled by
        // strip_zero_width inside normalize_word instead.
        assert_eq!(split_js_whitespace("a\u{200B}b"), vec!["a\u{200B}b"]);
    }

    #[test]
    fn german_eszett_maps_to_ss_before_vocab_check() {
        let v = vocab(&['s', 't', 'r', 'a', 'e']);
        let result = normalize_word("straße", Language::De, &v);
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("strasse"));
    }

    #[test]
    fn uppercase_eszett_lowercases_then_maps_to_ss() {
        let v = vocab(&['g', 'r', 'o', 's']);
        let result = normalize_word("GROẞ", Language::De, &v);
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("gross"));
    }

    #[test]
    fn digit_bearing_word_is_unrepresentable_with_recorded_reason() {
        let v = vocab(&['a', 'v', 'l', 'b', 'e']);
        let result = normalize_word("room101", Language::En, &v);
        assert!(!result.representable);
        assert!(result.mapped.is_none());
        assert!(result.reason.as_deref().unwrap().contains("digit"));
    }

    #[test]
    fn empty_and_whitespace_only_input_yield_no_words() {
        let v = vocab(&['a']);
        assert_eq!(normalize_for_forced_alignment("", Language::En, &v).words.len(), 0);
        assert_eq!(normalize_for_forced_alignment("   \t\n  ", Language::En, &v).words.len(), 0);
    }

    #[test]
    fn oov_character_is_rejected_not_silently_accepted() {
        // Cyrillic "п" is deliberately absent from this test vocab (and from
        // the real en vocab) — proves the port did not become permissive.
        let v = vocab(&['h', 'e', 'l', 'o']);
        assert!(!v.contains(&'п'), "test premise: п must be absent from the vocab");
        let result = normalize_word("привет", Language::En, &v);
        assert!(!result.representable);
        assert!(result.reason.as_deref().unwrap().contains("is not in the en vocab"));
    }

    #[test]
    fn fold_then_strip_recovers_a_quoted_contraction() {
        let v = vocab(&['d', 'o', 'n', 't', '\'']);
        let result = normalize_word("\u{201C}don\u{2019}t.\u{201D}", Language::En, &v);
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("don't"));
    }

    #[test]
    fn zero_width_space_removed_mid_word() {
        let v = vocab(&['h', 'e', 'l', 'o']);
        let result = normalize_word("hel\u{200B}lo", Language::En, &v);
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("hello"));
    }

    #[test]
    fn vocab_chars_from_raw_vocab_excludes_special_tokens() {
        let mut map = serde_json::Map::new();
        map.insert("<pad>".to_string(), serde_json::json!(0));
        map.insert("|".to_string(), serde_json::json!(1));
        map.insert("a".to_string(), serde_json::json!(2));
        let chars = vocab_chars_from_raw_vocab(&map);
        assert_eq!(chars, vocab(&['a']));
    }
}

// ---------------------------------------------------------------------------
// Fixture parity — proves this port is byte-identical to the live TS module
// over the shared corpus. HARD GATE, all five languages.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod fixture_parity {
    use super::*;
    use std::collections::HashMap;

    #[derive(serde::Deserialize)]
    struct FixtureFile {
        entries: Vec<FixtureEntry>,
    }

    #[derive(serde::Deserialize)]
    struct FixtureEntry {
        language: String,
        input: String,
        #[allow(dead_code)]
        note: String,
        words: Vec<FixtureWord>,
        text: String,
    }

    #[derive(serde::Deserialize)]
    struct FixtureWord {
        input: String,
        representable: bool,
        mapped: Option<String>,
        reason: Option<String>,
    }

    fn fixtures_dir() -> std::path::PathBuf {
        std::path::PathBuf::from(format!("{}/../scripts/fixtures", env!("CARGO_MANIFEST_DIR")))
    }

    fn load_fixture() -> FixtureFile {
        let path = fixtures_dir().join("fa-text-normalize-fixture.json");
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
    }

    fn load_all_vocabs() -> HashMap<Language, HashSet<char>> {
        let mut map = HashMap::new();
        for lang in [Language::En, Language::Es, Language::Fr, Language::De, Language::Pt] {
            let path = fixtures_dir().join(format!("fa-vocab-{}.json", lang.code()));
            let chars = vocab_chars_from_path(&path).unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()));
            map.insert(lang, chars);
        }
        map
    }

    #[test]
    fn fixture_matches_rust_port_for_every_entry_all_five_languages() {
        let fixture = load_fixture();
        let vocabs = load_all_vocabs();
        assert!(!fixture.entries.is_empty(), "fixture must not be empty");

        let mut seen_languages: HashSet<&str> = HashSet::new();
        let mut mismatches = Vec::new();

        for entry in &fixture.entries {
            seen_languages.insert(entry.language.as_str());
            let language = Language::from_code(&entry.language)
                .unwrap_or_else(|| panic!("fixture entry has unknown language code: {}", entry.language));
            let vocab_chars = &vocabs[&language];

            let got = normalize_for_forced_alignment(&entry.input, language, vocab_chars);

            if got.text != entry.text {
                mismatches.push(format!(
                    "input {:?} ({}): text mismatch — got {:?}, want {:?}",
                    entry.input, entry.language, got.text, entry.text
                ));
                continue;
            }
            if got.words.len() != entry.words.len() {
                mismatches.push(format!(
                    "input {:?} ({}): word count mismatch — got {}, want {}",
                    entry.input,
                    entry.language,
                    got.words.len(),
                    entry.words.len()
                ));
                continue;
            }
            for (i, (got_word, want_word)) in got.words.iter().zip(entry.words.iter()).enumerate() {
                if got_word.input != want_word.input
                    || got_word.representable != want_word.representable
                    || got_word.mapped != want_word.mapped
                    || got_word.reason != want_word.reason
                {
                    mismatches.push(format!(
                        "input {:?} ({}) word[{i}]: got {got_word:?}, want input={:?} representable={} mapped={:?} reason={:?}",
                        entry.input, entry.language, want_word.input, want_word.representable, want_word.mapped, want_word.reason
                    ));
                }
            }
        }

        assert_eq!(
            seen_languages,
            HashSet::from(["en", "es", "fr", "de", "pt"]),
            "fixture must cover all five languages"
        );

        assert!(
            mismatches.is_empty(),
            "{} mismatch(es) between Rust port and TS-generated fixture:\n{}",
            mismatches.len(),
            mismatches.join("\n")
        );
    }

    #[test]
    fn fixture_oov_case_is_genuinely_rejected_by_both_reference_and_port() {
        // Non-vacuity check for the OOV-rejection requirement: the fixture's
        // Cyrillic case must (a) exist, (b) be recorded as unrepresentable by
        // the TS reference, and (c) the vocab it was checked against must
        // truly lack that character, so a permissive Rust port can't pass by
        // accident.
        let fixture = load_fixture();
        let vocabs = load_all_vocabs();

        let oov_entry = fixture
            .entries
            .iter()
            .find(|e| e.input.contains('п'))
            .expect("fixture must contain a genuine OOV (Cyrillic) case");

        let language = Language::from_code(&oov_entry.language).unwrap();
        assert!(
            !vocabs[&language].contains(&'п'),
            "test premise violated: the {} vocab must not contain 'п'",
            oov_entry.language
        );

        let oov_word = oov_entry.words.iter().find(|w| w.input.contains('п')).unwrap();
        assert!(!oov_word.representable, "fixture premise: TS reference must reject the OOV word");

        let got = normalize_word(&oov_word.input, language, &vocabs[&language]);
        assert!(!got.representable, "Rust port must also reject the OOV word — port must not be permissive");
        assert_eq!(got.reason, oov_word.reason);
    }
}
