// ---------------------------------------------------------------------------
// Forced-alignment vocab-aware text normalizer — Rust port (WS1 Task 5 Slice
// D3) of `src/services/faTextNormalize.ts`. That TS module is the source of
// truth for every rule below; this file is a byte-identical port, proven via
// the shared fixture `scripts/fixtures/fa-text-normalize-fixture.json`
// (generated by `scripts/generate-fa-text-fixture.ts` by driving the *live*
// TS module — never hand-derived) and this file's `fixture_parity` tests.
//
// UNCONDITIONAL — not behind `#[cfg(feature = "fa-inference")]` — so the
// default build (no ML dependency) still compiles and tests this module.
// Replaces `fa_onnx.rs`'s former ASCII-only placeholder tokenizer.
//
// DELIBERATE DEVIATIONS FROM A LITERAL, GENERAL-PURPOSE NFC/`\s` PORT (see
// each site below for detail — both are narrow, safe-by-construction, and
// were confirmed necessary by directly testing V8's actual behavior, not
// assumed from spec text alone):
//
//   1. NFC normalization. `normalizeWord`'s first step is
//      `rawWord.normalize('NFC')`. Rust's std has no Unicode normalization,
//      and this slice's scope caps Cargo dependency changes at the
//      `serde_json` feature-gate promotion (see `Cargo.toml`) — no new crate.
//      `compose_scoped_nfc` below hand-composes exactly the ~54
//      base(+case)/combining-mark pairs that produce the accented letters
//      actually present across the five shipped vocabs (verified by
//      `unicodedata.normalize('NFD', ch)` over the union of every non-ASCII
//      char in `scripts/fixtures/fa-vocab-*.json`, all single-mark — none of
//      the five vocabs contain a canonically-decomposable ligature or a
//      multi-mark precomposed character). A decomposed sequence outside this
//      table simply fails to compose and falls through unchanged — normal
//      per-character vocab-membership rejection then handles it exactly like
//      any other genuinely out-of-vocab character (safe fallback: worst case
//      is an unnecessary "unrepresentable", never a wrong composition).
//
//   2. Whitespace splitting. `normalizeForForcedAlignment` splits on JS's
//      `/\s+/`, whose `\s` class is ECMA-262's WhiteSpace+LineTerminator set
//      — notably INCLUDES U+FEFF (BOM/ZWNBSP) and EXCLUDES U+0085 (NEL).
//      Rust's `char::is_whitespace()` (Unicode White_Space property) is the
//      opposite on both points. Confirmed directly: in Node,
//      `"a﻿b".split(/\s+/)` -> `["a", "b"]` — FEFF splits a word in the
//      reference implementation, so a Rust port using `str::split_whitespace`
//      would silently diverge on that input. `is_js_whitespace` below
//      reproduces the exact ECMA-262 `\s` code point set instead.
// ---------------------------------------------------------------------------

// Compiled in every config (see module doc comment above), but this module's
// only non-test consumer (`fa_onnx.rs`) is itself gated on `fa-inference` —
// so with that feature off, every item here is genuinely unreachable outside
// of this file's own `#[cfg(test)]` modules. Mirrors the same
// `#[cfg_attr(not(feature = "fa-inference"), allow(dead_code))]` convention
// `fa.rs` already uses for its own multi-config items, applied once at the
// module level here since the entire public surface is in the same boat.
#![cfg_attr(not(feature = "fa-inference"), allow(dead_code))]

use std::collections::HashMap;
use std::collections::HashSet;
use std::fmt;
use std::path::Path;

// ---------------------------------------------------------------------------
// Language
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Language {
    En,
    Es,
    Fr,
    De,
    Pt,
}

impl Language {
    pub fn code(self) -> &'static str {
        match self {
            Language::En => "en",
            Language::Es => "es",
            Language::Fr => "fr",
            Language::De => "de",
            Language::Pt => "pt",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "en" => Some(Language::En),
            "es" => Some(Language::Es),
            "fr" => Some(Language::Fr),
            "de" => Some(Language::De),
            "pt" => Some(Language::Pt),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Vocab loading — `vocabCharsFromRawVocab`'s port, plus a path-based loader
// since Rust (unlike the TS caller) has no "already-parsed-JSON-in-hand"
// entry point of its own. Vocab is always loaded from a CALLER-SUPPLIED path
// — this module never embeds, hardcodes, or resolves a vocab path itself
// (never reaches into `src-tauri/models/`).
// ---------------------------------------------------------------------------

/// Vocab-JSON entries that are CTC bookkeeping tokens, not literal spellable
/// characters — `|` is wav2vec2's word-delimiter token, not a printable pipe.
const NON_CHARACTER_VOCAB_TOKENS: &[&str] = &["<pad>", "<s>", "</s>", "<unk>", "|"];

/// Error type for [`vocab_chars_from_path`] — the only non-test-exclusive
/// consumer would be a future caller loading vocab from a real filesystem
/// path; see that function's doc comment for why it's test-only today.
#[cfg_attr(not(test), allow(dead_code))]
#[derive(Debug)]
pub enum TextError {
    Io(String),
    Json(String),
    MissingVocabField,
}

impl fmt::Display for TextError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TextError::Io(msg) => write!(f, "failed to read vocab file: {msg}"),
            TextError::Json(msg) => write!(f, "failed to parse vocab JSON: {msg}"),
            TextError::MissingVocabField => write!(f, "vocab JSON missing a \"vocab\" object field"),
        }
    }
}

impl std::error::Error for TextError {}

/// Derives the set of literal, spellable characters from a model's raw
/// `vocab.json` object (as committed verbatim in `scripts/fixtures/
/// fa-vocab-<lang>.json`'s `vocab` field) — i.e. every key except the CTC
/// special/delimiter tokens above. Mirrors `vocabCharsFromRawVocab`.
pub fn vocab_chars_from_raw_vocab(raw_vocab: &serde_json::Map<String, serde_json::Value>) -> HashSet<char> {
    let mut chars = HashSet::new();
    for key in raw_vocab.keys() {
        if NON_CHARACTER_VOCAB_TOKENS.contains(&key.as_str()) {
            continue;
        }
        if key.chars().count() == 1 {
            chars.insert(key.chars().next().unwrap());
        }
    }
    chars
}

/// Reads and parses a `fa-vocab-<lang>.json`-shaped file at `path` (caller-
/// supplied — this function performs no path resolution of its own) and
/// returns its vocab-membership character set. Used by this crate's own
/// tests to load `scripts/fixtures/fa-vocab-<lang>.json` directly (mirroring
/// `faTextNormalize.test.ts`'s `loadVocabChars`); `fa_onnx.rs`'s production
/// path embeds its vocab JSON via `include_str!` instead (see that file) and
/// so never calls this — hence `allow(dead_code)` outside test builds.
#[cfg_attr(not(test), allow(dead_code))]
pub fn vocab_chars_from_path(path: &Path) -> Result<HashSet<char>, TextError> {
    let contents = std::fs::read_to_string(path).map_err(|e| TextError::Io(e.to_string()))?;
    let parsed: serde_json::Value = serde_json::from_str(&contents).map_err(|e| TextError::Json(e.to_string()))?;
    let vocab_obj = parsed
        .get("vocab")
        .and_then(|v| v.as_object())
        .ok_or(TextError::MissingVocabField)?;
    Ok(vocab_chars_from_raw_vocab(vocab_obj))
}

// ---------------------------------------------------------------------------
// Compositional cardinal-number generation (WS2 T3.2 Step 3b-iii) — byte-
// identical port of `faTextNormalize.ts`'s equivalent section (see that
// file's own module comment above `FaJoiner` for the full design and its
// no-magnitude-cap rationale). Replaces the four former per-language capped
// 0-30 tables below (Spanish/German/Portuguese/French) and adds English
// (previously unhandled on the FA side). Reads the SAME five
// `scripts/fixtures/fa-cardinal-<lang>.json` files the TS side reads —
// embedded via `include_str!` (mirroring `fa_onnx.rs`'s own vocab-embedding
// pattern, `vocab_json_for`/`load_vocab`) so this crate never hardcodes a
// cardinal-word table of its own either.
// ---------------------------------------------------------------------------

/// Mirrors `FaJoiner`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct FaJoiner {
    #[serde(rename = "type")]
    pub kind: String,
    pub text: Option<String>,
}

/// Mirrors `FaHundredConfig`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct FaHundredConfig {
    pub word: String,
    #[serde(rename = "combiningWord")]
    pub combining_word: String,
    #[serde(rename = "multiplierForm")]
    pub multiplier_form: String,
    #[serde(rename = "multiplierWords")]
    pub multiplier_words: Option<HashMap<String, String>>,
    #[serde(rename = "dropsOneMultiplier")]
    pub drops_one_multiplier: bool,
    #[serde(rename = "countWordOverride")]
    pub count_word_override: Option<String>,
    #[serde(rename = "regularMultiplierJoiner")]
    pub regular_multiplier_joiner: Option<FaJoiner>,
    #[serde(rename = "remainderJoiner")]
    pub remainder_joiner: FaJoiner,
    #[serde(rename = "pluralizesWhenExactMultiple")]
    pub pluralizes_when_exact_multiple: Option<bool>,
    #[serde(rename = "pluralSuffix")]
    pub plural_suffix: Option<String>,
}

/// Mirrors `FaScaleLevel`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct FaScaleLevel {
    pub value: u64,
    pub word: String,
    #[serde(rename = "pluralWord")]
    pub plural_word: String,
    #[serde(rename = "dropsOneMultiplier")]
    pub drops_one_multiplier: bool,
    #[serde(rename = "countWordOverride")]
    pub count_word_override: Option<String>,
    pub joiner: FaJoiner,
}

/// Mirrors `FaYearReadingPolicy`/`FaYearReading["selectionPolicy"]`'s
/// `string | object | null` union — `#[serde(untagged)]` picks the object
/// form when the JSON value is an object, the plain-string form when it's a
/// string; a JSON `null` deserializes as `None` on the wrapping
/// `Option<FaYearSelectionPolicy>` field in [`FaYearReading`] rather than a
/// variant of this enum.
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(untagged)]
pub enum FaYearSelectionPolicy {
    Threshold {
        #[allow(dead_code)]
        name: String,
        threshold: u64,
        #[serde(rename = "atOrAboveThreshold")]
        at_or_above_threshold: String,
        #[serde(rename = "belowThreshold")]
        below_threshold: String,
    },
    Named(String),
}

/// Mirrors `FaYearReading`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct FaYearReading {
    #[serde(rename = "rangeMin")]
    pub range_min: u64,
    #[serde(rename = "rangeMax")]
    pub range_max: u64,
    #[allow(dead_code)]
    #[serde(rename = "modFloor")]
    pub mod_floor: u64,
    #[allow(dead_code)]
    pub candidates: Vec<String>,
    #[serde(rename = "selectionPolicy")]
    pub selection_policy: Option<FaYearSelectionPolicy>,
}

/// Mirrors `FaCardinalData` — the full shape of one
/// `scripts/fixtures/fa-cardinal-<lang>.json` file (its `_provenance`/
/// `rationale`/`matcherParityNote`/`note` metadata fields are intentionally
/// not modeled here, same as the TS side).
#[derive(Debug, Clone, serde::Deserialize)]
pub struct FaCardinalData {
    #[serde(rename = "cardinals0to99")]
    pub cardinals_0_to_99: HashMap<String, String>,
    pub hundred: FaHundredConfig,
    pub scale: Vec<FaScaleLevel>,
    #[serde(rename = "yearReading")]
    pub year_reading: FaYearReading,
}

/// Reads and parses a `fa-cardinal-<lang>.json` file at `path` (caller-
/// supplied — this function performs no path resolution of its own). Test-
/// only, mirroring [`vocab_chars_from_path`]'s own role: this crate's tests
/// load the real fixture directly; `fa_onnx.rs`'s production path embeds its
/// copy via `include_str!` instead (`cardinal_json_for` below) and never
/// calls this.
#[cfg_attr(not(test), allow(dead_code))]
pub fn cardinal_data_from_path(path: &Path) -> Result<FaCardinalData, TextError> {
    let contents = std::fs::read_to_string(path).map_err(|e| TextError::Io(e.to_string()))?;
    serde_json::from_str(&contents).map_err(|e| TextError::Json(e.to_string()))
}

/// `null`/absent and `{"type": "concatenate"}` both insert nothing;
/// `{"type": "space", "text": null}` inserts a bare space; `{"type":
/// "space", "text": "e"}` inserts `" e "`. Mirrors `joinerSeparator`.
fn joiner_separator(joiner: Option<&FaJoiner>) -> String {
    match joiner {
        None => String::new(),
        Some(j) if j.kind == "concatenate" => String::new(),
        Some(j) => match &j.text {
            Some(t) => format!(" {t} "),
            None => " ".to_string(),
        },
    }
}

/// Direct lookup into the data file's own 0-99 table. Mirrors
/// `cardinal0to99`.
fn cardinal_0_to_99(n: u64, data: &FaCardinalData) -> String {
    data.cardinals_0_to_99
        .get(&n.to_string())
        .unwrap_or_else(|| panic!("fa cardinal data: cardinals0to99 missing entry for {n}"))
        .clone()
}

/// Composes 100-999 per `data.hundred`'s configuration. Mirrors
/// `composeHundred` — see that function's own doc comment (and
/// `FaHundredConfig`'s, in faTextNormalize.ts) for the three hundred-grammar
/// shapes this models.
fn compose_hundred(n: u64, data: &FaCardinalData) -> String {
    let hundred = &data.hundred;
    let multiplier = n / 100;
    let remainder = n % 100;

    let head: String = if hundred.multiplier_form == "fused" {
        if multiplier == 1 {
            if remainder == 0 { hundred.word.clone() } else { hundred.combining_word.clone() }
        } else {
            hundred
                .multiplier_words
                .as_ref()
                .and_then(|m| m.get(&(multiplier * 100).to_string()))
                .unwrap_or_else(|| panic!("fa cardinal data: hundred.multiplierWords missing entry for {}", multiplier * 100))
                .clone()
        }
    } else {
        let multiplier_part: String = if multiplier == 1 && hundred.drops_one_multiplier {
            String::new()
        } else if multiplier == 1 && hundred.count_word_override.is_some() {
            hundred.count_word_override.clone().unwrap()
        } else if let Some(word) = hundred.multiplier_words.as_ref().and_then(|m| m.get(&multiplier.to_string())) {
            word.clone()
        } else {
            cardinal_0_to_99(multiplier, data)
        };

        let mut hundred_word = hundred.word.clone();
        if hundred.pluralizes_when_exact_multiple.unwrap_or(false)
            && hundred.plural_suffix.is_some()
            && remainder == 0
            && multiplier > 1
        {
            hundred_word.push_str(hundred.plural_suffix.as_deref().unwrap());
        }

        if multiplier_part.is_empty() {
            hundred_word
        } else if hundred.multiplier_form == "concatenate" {
            format!("{multiplier_part}{hundred_word}")
        } else {
            format!("{multiplier_part}{}{hundred_word}", joiner_separator(hundred.regular_multiplier_joiner.as_ref()))
        }
    };

    if remainder == 0 {
        return head;
    }
    let tail = cardinal_0_to_99(remainder, data);
    format!("{head}{}{tail}", joiner_separator(Some(&hundred.remainder_joiner)))
}

/// Composes `n` at and above one scale level (thousand, million, ...).
/// Mirrors `composeScaleLevel`.
fn compose_scale_level(n: u64, level: &FaScaleLevel, data: &FaCardinalData) -> String {
    let multiplier = n / level.value;
    let remainder = n % level.value;

    let multiplier_part: String = if multiplier == 1 && level.drops_one_multiplier {
        String::new()
    } else if multiplier == 1 && level.count_word_override.is_some() {
        level.count_word_override.clone().unwrap()
    } else {
        cardinal_to_words(multiplier, data)
    };
    let scale_word = if multiplier == 1 { level.word.clone() } else { level.plural_word.clone() };
    let head = if multiplier_part.is_empty() {
        scale_word
    } else if level.joiner.kind == "concatenate" {
        format!("{multiplier_part}{scale_word}")
    } else {
        format!("{multiplier_part}{}{scale_word}", joiner_separator(Some(&level.joiner)))
    };

    if remainder == 0 {
        return head;
    }
    let tail = cardinal_to_words(remainder, data);
    if level.joiner.kind == "concatenate" { format!("{head}{tail}") } else { format!("{head} {tail}") }
}

/// Full literal/arithmetic cardinal reading of any non-negative integer, per
/// `data`'s own composition rules. Mirrors `cardinalToWords`.
fn cardinal_to_words(n: u64, data: &FaCardinalData) -> String {
    if n < 100 {
        return cardinal_0_to_99(n, data);
    }
    if n < 1000 {
        return compose_hundred(n, data);
    }
    let mut levels: Vec<&FaScaleLevel> = data.scale.iter().collect();
    levels.sort_by(|a, b| b.value.cmp(&a.value));
    for level in levels {
        if n >= level.value {
            return compose_scale_level(n, level, data);
        }
    }
    panic!("fa cardinal data: no scale level applies to {n}");
}

/// The "pair"/"hundertgruppe" year-reading shapes. Mirrors
/// `composeYearReading`.
fn compose_year_reading(n: u64, candidate: &str, data: &FaCardinalData) -> String {
    if candidate == "compound" {
        return cardinal_to_words(n, data);
    }
    let high = cardinal_0_to_99(n / 100, data);
    let low = cardinal_0_to_99(n % 100, data);
    if candidate == "pair" {
        return format!("{high} {low}");
    }
    if candidate == "hundertgruppe" {
        return if data.hundred.multiplier_form == "concatenate" {
            format!("{high}{}{low}", data.hundred.word)
        } else {
            format!("{high} {} {low}", data.hundred.word)
        };
    }
    panic!("fa cardinal data: unknown yearReading candidate \"{candidate}\"");
}

/// Resolves `yearReading.selectionPolicy` to the candidate name that applies
/// to this specific `n`. Mirrors `selectYearCandidate`.
fn select_year_candidate(n: u64, policy: &Option<FaYearSelectionPolicy>) -> String {
    match policy {
        None => panic!("fa cardinal data: yearReading.selectionPolicy is unset (null) for this language"),
        Some(FaYearSelectionPolicy::Named(name)) => name.clone(),
        Some(FaYearSelectionPolicy::Threshold { threshold, at_or_above_threshold, below_threshold, .. }) => {
            if (n % 100) >= *threshold { at_or_above_threshold.clone() } else { below_threshold.clone() }
        }
    }
}

/// Entry point replacing the four former per-language `expand_*_cardinal`
/// functions below — now shared across all five languages and fully data-
/// driven. Mirrors `expandCardinalToken`.
fn expand_cardinal_token(stripped: &str, data: &FaCardinalData) -> Option<String> {
    if stripped.is_empty() || !stripped.chars().all(|c| c.is_ascii_digit()) {
        return None;
    }
    if stripped.len() > 1 && stripped.starts_with('0') {
        return None;
    }
    let n: u64 = stripped.parse().ok()?;
    let yr = &data.year_reading;
    if stripped.len() == 4 && n >= yr.range_min && n <= yr.range_max {
        let candidate = select_year_candidate(n, &yr.selection_policy);
        return Some(compose_year_reading(n, &candidate, data));
    }
    Some(cardinal_to_words(n, data))
}

// ---------------------------------------------------------------------------
// NFC (scoped) — see module doc comment, deviation 1.
// ---------------------------------------------------------------------------

/// (base, combining mark, precomposed) — every base(+case)/mark pair needed
/// to reconstruct the accented letters present across the five shipped
/// vocabs when they arrive NFD-decomposed. Generated from
/// `unicodedata.normalize('NFD', ch)` over each vocab's non-ASCII characters
/// — see module doc comment.
const NFC_COMPOSE: &[(char, char, char)] = &[
    ('a', '\u{0300}', 'à'),
    ('A', '\u{0300}', 'À'),
    ('a', '\u{0301}', 'á'),
    ('A', '\u{0301}', 'Á'),
    ('a', '\u{0302}', 'â'),
    ('A', '\u{0302}', 'Â'),
    ('a', '\u{0308}', 'ä'),
    ('A', '\u{0308}', 'Ä'),
    ('a', '\u{0303}', 'ã'),
    ('A', '\u{0303}', 'Ã'),
    ('c', '\u{0327}', 'ç'),
    ('C', '\u{0327}', 'Ç'),
    ('c', '\u{0301}', 'ć'),
    ('C', '\u{0301}', 'Ć'),
    ('c', '\u{030c}', 'č'),
    ('C', '\u{030c}', 'Č'),
    ('e', '\u{0300}', 'è'),
    ('E', '\u{0300}', 'È'),
    ('e', '\u{0301}', 'é'),
    ('E', '\u{0301}', 'É'),
    ('e', '\u{0302}', 'ê'),
    ('E', '\u{0302}', 'Ê'),
    ('e', '\u{0308}', 'ë'),
    ('E', '\u{0308}', 'Ë'),
    ('i', '\u{0301}', 'í'),
    ('I', '\u{0301}', 'Í'),
    ('i', '\u{0302}', 'î'),
    ('I', '\u{0302}', 'Î'),
    ('i', '\u{0308}', 'ï'),
    ('I', '\u{0308}', 'Ï'),
    ('n', '\u{0303}', 'ñ'),
    ('N', '\u{0303}', 'Ñ'),
    ('o', '\u{0301}', 'ó'),
    ('O', '\u{0301}', 'Ó'),
    ('o', '\u{0302}', 'ô'),
    ('O', '\u{0302}', 'Ô'),
    ('o', '\u{0308}', 'ö'),
    ('O', '\u{0308}', 'Ö'),
    ('o', '\u{0303}', 'õ'),
    ('O', '\u{0303}', 'Õ'),
    ('o', '\u{0304}', 'ō'),
    ('O', '\u{0304}', 'Ō'),
    ('s', '\u{030c}', 'š'),
    ('S', '\u{030c}', 'Š'),
    ('s', '\u{0326}', 'ș'),
    ('S', '\u{0326}', 'Ș'),
    ('u', '\u{0300}', 'ù'),
    ('U', '\u{0300}', 'Ù'),
    ('u', '\u{0301}', 'ú'),
    ('U', '\u{0301}', 'Ú'),
    ('u', '\u{0302}', 'û'),
    ('U', '\u{0302}', 'Û'),
    ('u', '\u{0308}', 'ü'),
    ('U', '\u{0308}', 'Ü'),
];

fn compose_pair(base: char, mark: char) -> Option<char> {
    NFC_COMPOSE.iter().find(|&&(b, m, _)| b == base && m == mark).map(|&(_, _, c)| c)
}

/// Scoped NFC composition — see module doc comment, deviation 1.
fn compose_scoped_nfc(word: &str) -> String {
    let mut out = String::with_capacity(word.len());
    let mut pending: Option<char> = None;
    for ch in word.chars() {
        match pending {
            Some(base) => match compose_pair(base, ch) {
                Some(composed) => pending = Some(composed),
                None => {
                    out.push(base);
                    pending = Some(ch);
                }
            },
            None => pending = Some(ch),
        }
    }
    if let Some(base) = pending {
        out.push(base);
    }
    out
}

// ---------------------------------------------------------------------------
// JS-`\s`-equivalent whitespace splitting — see module doc comment, deviation 2.
// ---------------------------------------------------------------------------

fn is_js_whitespace(ch: char) -> bool {
    matches!(
        ch,
        '\u{0009}'..='\u{000D}'
            | '\u{0020}'
            | '\u{00A0}'
            | '\u{1680}'
            | '\u{2000}'..='\u{200A}'
            | '\u{2028}'
            | '\u{2029}'
            | '\u{202F}'
            | '\u{205F}'
            | '\u{3000}'
            | '\u{FEFF}'
    )
}

/// Mirrors `input.split(/\s+/).filter(w => w.length > 0)`.
fn split_js_whitespace(input: &str) -> Vec<&str> {
    input.split(is_js_whitespace).filter(|w| !w.is_empty()).collect()
}

// ---------------------------------------------------------------------------
// Zero-width stripping, typographic folding, boundary-punctuation stripping
// ---------------------------------------------------------------------------

/// Zero-width/invisible characters — stripped wherever they occur in a token
/// (copy-paste artifacts, not meaningful word content): zero-width space,
/// zero-width non-joiner/joiner, BOM/zero-width no-break space, word joiner.
fn is_zero_width(ch: char) -> bool {
    matches!(ch, '\u{200B}' | '\u{200C}' | '\u{200D}' | '\u{FEFF}' | '\u{2060}')
}

fn strip_zero_width(word: &str) -> String {
    word.chars().filter(|&c| !is_zero_width(c)).collect()
}

/// Typographic variant -> ASCII target. Mirrors `FOLD_TARGETS`.
fn fold_target(ch: char) -> Option<char> {
    match ch {
        '\u{2018}' => Some('\''), // LEFT SINGLE QUOTATION MARK
        '\u{2019}' => Some('\''), // RIGHT SINGLE QUOTATION MARK
        '\u{02BC}' => Some('\''), // MODIFIER LETTER APOSTROPHE
        '\u{2010}' => Some('-'),  // HYPHEN
        '\u{2011}' => Some('-'),  // NON-BREAKING HYPHEN
        '\u{2013}' => Some('-'),  // EN DASH
        '\u{2014}' => Some('-'),  // EM DASH
        '\u{201C}' => Some('"'),  // LEFT DOUBLE QUOTATION MARK
        '\u{201D}' => Some('"'),  // RIGHT DOUBLE QUOTATION MARK
        '\u{201E}' => Some('"'),  // DOUBLE LOW-9 QUOTATION MARK
        '\u{201F}' => Some('"'),  // DOUBLE HIGH-REVERSED-9 QUOTATION MARK
        _ => None,
    }
}

/// Substitutes each typographic variant found anywhere in the token for its
/// ASCII target, but only when the target is actually a member of this
/// language's vocab — otherwise the variant is dropped (strip, not fold).
fn fold_typographic_variants(word: &str, vocab_chars: &HashSet<char>) -> String {
    let mut out = String::with_capacity(word.len());
    for ch in word.chars() {
        match fold_target(ch) {
            None => out.push(ch),
            Some(target) if vocab_chars.contains(&target) => out.push(target),
            Some(_) => {} // fold target absent from vocab — drop the character entirely.
        }
    }
    out
}

/// Word-boundary punctuation: stripped from a token's leading/trailing edges
/// only (never word-internal).
fn is_boundary_punct(ch: char) -> bool {
    matches!(ch, '.' | ',' | ';' | ':' | '?' | '!' | '"' | '«' | '»' | '(' | ')')
}

/// Strips boundary punctuation from a token's leading/trailing edges only,
/// repeatedly, so stacked marks (e.g. a quote-and-comma pair) fully clear.
fn strip_boundary_punctuation(word: &str) -> &str {
    word.trim_matches(is_boundary_punct)
}

// ---------------------------------------------------------------------------
// German ß -> ss
// ---------------------------------------------------------------------------

/// German's vocab has no `ß` — the standard `ß` -> `ss` expansion is applied
/// before the vocab-membership check, not treated as an unrepresentable
/// character. Applied only for `de`; a no-op otherwise.
fn apply_language_specific_substitutions(word: &str, language: Language) -> String {
    if language == Language::De {
        word.replace('ß', "ss")
    } else {
        word.to_string()
    }
}

// ---------------------------------------------------------------------------
// French elision (Part H.5 Rule 1) - mirrors faTextNormalize.ts's own
// comment block in intent: an elided word stays ONE token (this module's
// split_js_whitespace never treats apostrophe as a separator, so this was
// already true before this rule); the one genuine gap this rule closes is a
// grave accent (a backtick) used as an apostrophe typo/OCR substitute at a
// recognized elision boundary (prefix + apostrophe-like char +
// vowel-or-mute-h). French-only, shape-gated by construction.
// ---------------------------------------------------------------------------

/// Elidable French forms. Mirrors `FRENCH_ELISION_PREFIXES`.
const FRENCH_ELISION_PREFIXES: &[&str] = &["qu", "l", "d", "j", "n", "s", "t", "m", "c"];

/// Elision only applies before a vowel or a mute h. Mirrors
/// `FRENCH_ELISION_FOLLOWERS`.
fn is_french_elision_follower(ch: char) -> bool {
    matches!(
        ch,
        'a' | 'e' | 'i' | 'o' | 'u' | 'y' | 'h'
            | 'à' | 'â' | 'ä' | 'é' | 'è' | 'ê' | 'ë' | 'î' | 'ï' | 'ô' | 'ö' | 'ù' | 'û' | 'ü' | 'œ'
    )
}

/// French-only: a backtick standing in for an apostrophe at a recognized
/// elision boundary folds to the vocab's straight apostrophe. Mirrors
/// `foldFrenchElisionBacktick`; operates on `char`s (not bytes) throughout
/// so multi-byte UTF-8 followers (e.g. `e-acute`) never cause a slice panic.
fn fold_french_elision_backtick(word: &str, vocab_chars: &HashSet<char>) -> String {
    if !vocab_chars.contains(&'\'') {
        return word.to_string();
    }
    let chars: Vec<char> = word.chars().collect();
    for prefix in FRENCH_ELISION_PREFIXES {
        let prefix_chars: Vec<char> = prefix.chars().collect();
        let prefix_len = prefix_chars.len();
        if chars.len() < prefix_len + 2 || chars[..prefix_len] != prefix_chars[..] {
            continue;
        }
        if chars[prefix_len] != '`' {
            continue;
        }
        if !is_french_elision_follower(chars[prefix_len + 1]) {
            continue;
        }
        let mut out = String::with_capacity(word.len());
        out.extend(&chars[..prefix_len]);
        out.push('\'');
        out.extend(&chars[prefix_len + 1..]);
        return out;
    }
    word.to_string()
}

// ---------------------------------------------------------------------------
// Word / phrase normalization
// ---------------------------------------------------------------------------

/// One normalized word (or the reason it couldn't be). Mirrors `FaWordResult`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WordResult {
    /// The original whitespace-delimited slice, before any mapping.
    pub input: String,
    pub representable: bool,
    /// `Some` iff `representable` — every character here is a vocab member.
    pub mapped: Option<String>,
    /// `Some` iff NOT `representable` — why this word was dropped.
    pub reason: Option<String>,
}

/// Mirrors `FaNormalizeResult`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NormalizeResult {
    /// One entry per whitespace-delimited word in the input, in order.
    pub words: Vec<WordResult>,
    /// Representable words' `mapped` text, single-space-joined.
    pub text: String,
}

/// Normalizes one already-whitespace-isolated word: scoped-NFC + lowercase,
/// the German ß->ss substitution, zero-width stripping, typographic folding,
/// boundary-punctuation stripping, then a data-driven cardinal-number
/// expansion (`expand_cardinal_token`, all five languages, WS2 T3.2 Step
/// 3b-iii), then a digit check and a per-character vocab membership check
/// (skipping the space character, which a multi-word compositional reading
/// may now contain structurally — a fragment delimiter, not a spellable
/// vocab character). Mirrors `normalizeWord`.
pub fn normalize_word(raw_word: &str, language: Language, vocab_chars: &HashSet<char>, cardinal_data: &FaCardinalData) -> WordResult {
    let nfc = compose_scoped_nfc(raw_word);
    let lowered = nfc.to_lowercase();
    let substituted = apply_language_specific_substitutions(&lowered, language);
    let elision_folded = if language == Language::Fr {
        fold_french_elision_backtick(&substituted, vocab_chars)
    } else {
        substituted
    };
    let dezero_widthed = strip_zero_width(&elision_folded);
    let folded = fold_typographic_variants(&dezero_widthed, vocab_chars);
    let stripped = strip_boundary_punctuation(&folded);

    if stripped.is_empty() {
        return WordResult {
            input: raw_word.to_string(),
            representable: false,
            mapped: None,
            reason: Some(format!(
                "reduced to nothing by fold/strip — no word content remained (word: \"{raw_word}\")"
            )),
        };
    }

    let cardinal_expansion = expand_cardinal_token(stripped, cardinal_data);
    let candidate: String = cardinal_expansion.clone().unwrap_or_else(|| stripped.to_string());

    if cardinal_expansion.is_none() && stripped.chars().any(|c| c.is_ascii_digit()) {
        return WordResult {
            input: raw_word.to_string(),
            representable: false,
            mapped: None,
            reason: Some(format!(
                "contains a digit — number expansion is Phase 3b, out of scope (word: \"{raw_word}\")"
            )),
        };
    }

    for ch in candidate.chars() {
        if ch == ' ' {
            continue; // fragment delimiter of a multi-word compositional reading, not a spellable vocab character
        }
        if !vocab_chars.contains(&ch) {
            return WordResult {
                input: raw_word.to_string(),
                representable: false,
                mapped: None,
                reason: Some(format!(
                    "character \"{ch}\" is not in the {} vocab (word: \"{raw_word}\")",
                    language.code()
                )),
            };
        }
    }

    WordResult { input: raw_word.to_string(), representable: true, mapped: Some(candidate), reason: None }
}

/// Normalizes a word or whitespace-separated phrase against one language's
/// CTC vocab. `cardinal_data` is that language's parsed `fa-cardinal-
/// <lang>.json` (WS2 T3.2 Step 3b-iii). Mirrors `normalizeForForcedAlignment`.
pub fn normalize_for_forced_alignment(
    input: &str,
    language: Language,
    vocab_chars: &HashSet<char>,
    cardinal_data: &FaCardinalData,
) -> NormalizeResult {
    let raw_words = split_js_whitespace(input);
    let words: Vec<WordResult> = raw_words.iter().map(|w| normalize_word(w, language, vocab_chars, cardinal_data)).collect();
    let text = words
        .iter()
        .filter(|w| w.representable)
        .map(|w| w.mapped.as_deref().unwrap())
        .collect::<Vec<_>>()
        .join(" ");
    NormalizeResult { words, text }
}

// ---------------------------------------------------------------------------
// Unit tests — pipeline mechanics not already covered by fixture parity below
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn vocab(chars: &[char]) -> HashSet<char> {
        chars.iter().copied().collect()
    }

    /// Loads a language's REAL `fa-cardinal-<lang>.json` fixture (WS2 T3.2
    /// Step 3b-iii) — used by every test in this module that needs a
    /// `cardinal_data` argument, whether or not that specific test exercises
    /// cardinal expansion (mirrors `faTextNormalize.test.ts`'s
    /// `loadCardinalData`, which does the same for the TS-side tests).
    fn cardinal_data_for(lang: Language) -> FaCardinalData {
        let path = std::path::PathBuf::from(format!(
            "{}/../scripts/fixtures/fa-cardinal-{}.json",
            env!("CARGO_MANIFEST_DIR"),
            lang.code()
        ));
        cardinal_data_from_path(&path).unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()))
    }

    /// Loads a language's REAL `fa-vocab-<lang>.json` fixture — used by the
    /// compositional cardinal-number generator tests below, which (unlike
    /// this module's other narrow hand-built vocabs) need arbitrary-
    /// magnitude coverage (hundreds/thousands/millions), not just a fixed
    /// 0-30 letter set.
    fn real_vocab_for(lang: Language) -> HashSet<char> {
        let path = std::path::PathBuf::from(format!(
            "{}/../scripts/fixtures/fa-vocab-{}.json",
            env!("CARGO_MANIFEST_DIR"),
            lang.code()
        ));
        vocab_chars_from_path(&path).unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()))
    }

    #[test]
    fn compose_scoped_nfc_recomposes_decomposed_accent() {
        // "e" + COMBINING ACUTE ACCENT -> "é"
        let decomposed = "e\u{0301}";
        assert_eq!(compose_scoped_nfc(decomposed), "é");
    }

    #[test]
    fn compose_scoped_nfc_leaves_already_precomposed_untouched() {
        assert_eq!(compose_scoped_nfc("café"), "café");
    }

    #[test]
    fn compose_scoped_nfc_leaves_unknown_combining_sequence_unchanged() {
        // COMBINING DOT ABOVE on "z" isn't in the scoped table for any
        // shipped vocab — must pass through untouched (safe fallback), not
        // silently merge or vanish.
        let input = "z\u{0307}";
        assert_eq!(compose_scoped_nfc(input), input);
    }

    #[test]
    fn split_js_whitespace_treats_bom_as_a_splitter_like_v8_does() {
        // Confirmed via node: "a﻿b".split(/\s+/) -> ["a", "b"].
        assert_eq!(split_js_whitespace("a\u{FEFF}b"), vec!["a", "b"]);
    }

    #[test]
    fn split_js_whitespace_does_not_split_on_zero_width_space() {
        // U+200B is not in JS's \s class — stays one token, handled by
        // strip_zero_width inside normalize_word instead.
        assert_eq!(split_js_whitespace("a\u{200B}b"), vec!["a\u{200B}b"]);
    }

    #[test]
    fn german_eszett_maps_to_ss_before_vocab_check() {
        let v = vocab(&['s', 't', 'r', 'a', 'e']);
        let result = normalize_word("straße", Language::De, &v, &cardinal_data_for(Language::De));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("strasse"));
    }

    #[test]
    fn uppercase_eszett_lowercases_then_maps_to_ss() {
        let v = vocab(&['g', 'r', 'o', 's']);
        let result = normalize_word("GROẞ", Language::De, &v, &cardinal_data_for(Language::De));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("gross"));
    }

    #[test]
    fn digit_bearing_word_is_unrepresentable_with_recorded_reason() {
        let v = vocab(&['a', 'v', 'l', 'b', 'e']);
        let result = normalize_word("room101", Language::En, &v, &cardinal_data_for(Language::En));
        assert!(!result.representable);
        assert!(result.mapped.is_none());
        assert!(result.reason.as_deref().unwrap().contains("digit"));
    }

    #[test]
    fn empty_and_whitespace_only_input_yield_no_words() {
        let v = vocab(&['a']);
        let cd = cardinal_data_for(Language::En);
        assert_eq!(normalize_for_forced_alignment("", Language::En, &v, &cd).words.len(), 0);
        assert_eq!(normalize_for_forced_alignment("   \t\n  ", Language::En, &v, &cd).words.len(), 0);
    }

    #[test]
    fn oov_character_is_rejected_not_silently_accepted() {
        // Cyrillic "п" is deliberately absent from this test vocab (and from
        // the real en vocab) — proves the port did not become permissive.
        let v = vocab(&['h', 'e', 'l', 'o']);
        assert!(!v.contains(&'п'), "test premise: п must be absent from the vocab");
        let result = normalize_word("привет", Language::En, &v, &cardinal_data_for(Language::En));
        assert!(!result.representable);
        assert!(result.reason.as_deref().unwrap().contains("is not in the en vocab"));
    }

    #[test]
    fn fold_then_strip_recovers_a_quoted_contraction() {
        let v = vocab(&['d', 'o', 'n', 't', '\'']);
        let result = normalize_word("\u{201C}don\u{2019}t.\u{201D}", Language::En, &v, &cardinal_data_for(Language::En));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("don't"));
    }

    #[test]
    fn zero_width_space_removed_mid_word() {
        let v = vocab(&['h', 'e', 'l', 'o']);
        let result = normalize_word("hel\u{200B}lo", Language::En, &v, &cardinal_data_for(Language::En));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("hello"));
    }

    #[test]
    fn vocab_chars_from_raw_vocab_excludes_special_tokens() {
        let mut map = serde_json::Map::new();
        map.insert("<pad>".to_string(), serde_json::json!(0));
        map.insert("|".to_string(), serde_json::json!(1));
        map.insert("a".to_string(), serde_json::json!(2));
        let chars = vocab_chars_from_raw_vocab(&map);
        assert_eq!(chars, vocab(&['a']));
    }

    // -- French elision (Part H.5 Rule 1) -----------------------------------

    fn fr_vocab() -> HashSet<char> {
        vocab(&['l', 'o', 'i', 's', 'e', 'a', 'u', 'h', 'm', 'd', 'q', 'j', 'n', 't', 'v', 'x', 'b', '\''])
    }

    #[test]
    fn elision_stays_one_token_straight_apostrophe_unchanged() {
        let result = normalize_word("l'oiseau", Language::Fr, &fr_vocab(), &cardinal_data_for(Language::Fr));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("l'oiseau"));
    }

    #[test]
    fn elision_mute_h_backtick_folds_to_apostrophe() {
        let result = normalize_word("l`homme", Language::Fr, &fr_vocab(), &cardinal_data_for(Language::Fr));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("l'homme"));
    }

    #[test]
    fn aspirate_h_word_is_not_elided_stays_two_separate_tokens() {
        let v = fr_vocab();
        let result = normalize_for_forced_alignment("le hibou", Language::Fr, &v, &cardinal_data_for(Language::Fr));
        assert_eq!(result.text, "le hibou");
        assert_eq!(result.words.len(), 2);
        assert!(result.words[0].representable && result.words[1].representable);
    }

    #[test]
    fn curly_apostrophe_variant_matches_straight_and_backtick_results() {
        let v = fr_vocab();
        let straight = normalize_word("l'oiseau", Language::Fr, &v, &cardinal_data_for(Language::Fr));
        let curly = normalize_word("l\u{2019}oiseau", Language::Fr, &v, &cardinal_data_for(Language::Fr));
        let backtick = normalize_word("l`oiseau", Language::Fr, &v, &cardinal_data_for(Language::Fr));
        assert_eq!(straight.mapped, curly.mapped);
        assert_eq!(straight.mapped, backtick.mapped);
    }

    #[test]
    fn two_letter_prefix_qu_folds_before_vowel() {
        let result = normalize_word("qu`il", Language::Fr, &fr_vocab(), &cardinal_data_for(Language::Fr));
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("qu'il"));
    }

    #[test]
    fn negative_backtick_mid_word_not_at_elision_boundary_is_not_folded() {
        // "aujourd'hui" is a fixed compound, not productive elision — the
        // "d'" substring is not word-initial, so the fold must not fire.
        // The backtick then simply isn't a vocab member and is rejected.
        let v = vocab(&['a', 'u', 'j', 'o', 'r', 'd', 'h', 'i']); // deliberately no apostrophe
        let result = normalize_word("aujourd`hui", Language::Fr, &v, &cardinal_data_for(Language::Fr));
        assert!(!result.representable);
        assert!(result.reason.as_deref().unwrap().contains('`'));
    }

    #[test]
    fn negative_consonant_follower_is_not_elision_and_is_not_folded() {
        // "j`veux": prefix "j" + backtick + a consonant ("v"), not a vowel
        // or mute h — not a grammatical elision shape, must not fold.
        let v = fr_vocab();
        let result = normalize_word("j`veux", Language::Fr, &v, &cardinal_data_for(Language::Fr));
        assert!(!result.representable);
        assert!(result.reason.as_deref().unwrap().contains('`'));
    }

    #[test]
    fn negative_backtick_is_language_gated_and_never_folds_outside_french() {
        let v = vocab(&['l', 'o', 'i', 's', 'e', 'a', 'u']); // no apostrophe, no backtick
        let result = normalize_word("l`oiseau", Language::En, &v, &cardinal_data_for(Language::En));
        assert!(!result.representable);
        assert!(result.reason.as_deref().unwrap().contains('`'));
    }

    // -- Compositional cardinal-number generation (WS2 T3.2 Step 3b-iii) ----
    //
    // Replaces the four former per-language CAPPED 0-30 tables (Spanish/
    // German/Portuguese/French, Part H.5 Rules 2-5) with a shared, data-
    // driven, unbounded generator. Every former "negative: N is past the
    // scope cap, stays dropped" case here is INVERTED on purpose — see
    // `faTextNormalize.test.ts`'s mirror-image rewrite for the same
    // corpus. Uses `real_vocab_for` (the actual shipped vocab), not a
    // narrow hand-built one, since these tests exercise arbitrary-magnitude
    // output.

    #[test]
    fn spanish_cardinal_generator() {
        let data = cardinal_data_for(Language::Es);
        let v = real_vocab_for(Language::Es);
        let cases: &[(&str, &str)] = &[
            ("0", "cero"),
            ("5", "cinco"),
            ("16", "dieciséis"),
            ("20", "veinte"),
            ("23", "veintitrés"),
            ("30", "treinta"),
            ("31", "treinta y uno"), // former scope cap — now representable
            ("99", "noventa y nueve"),
            ("100", "cien"),
            ("101", "ciento uno"),
            ("105", "ciento cinco"),
            ("200", "doscientos"),
            ("234", "doscientos treinta y cuatro"),
            ("1000", "mil"),
            ("1500", "mil quinientos"),
            ("1000000", "un millón"),
            ("2000000", "dos millones"),
        ];
        for (input, want) in cases {
            let result = normalize_word(input, Language::Es, &v, &data);
            assert!(result.representable, "{input} should be representable");
            assert_eq!(result.mapped.as_deref(), Some(*want), "input {input}");
        }
    }

    #[test]
    fn spanish_cardinal_survives_inside_a_phrase() {
        let v = real_vocab_for(Language::Es);
        let data = cardinal_data_for(Language::Es);
        let result = normalize_for_forced_alignment("cumplí 23 años", Language::Es, &v, &data);
        assert_eq!(result.text, "cumplí veintitrés años");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn german_cardinal_generator() {
        let data = cardinal_data_for(Language::De);
        let v = real_vocab_for(Language::De);
        let cases: &[(&str, &str)] = &[
            ("0", "null"),
            ("5", "fünf"),
            ("16", "sechzehn"),
            ("20", "zwanzig"),
            ("23", "dreiundzwanzig"),
            ("30", "dreissig"),
            ("31", "einunddreissig"), // former scope cap — now representable
            ("99", "neunundneunzig"),
            ("100", "einhundert"), // not "einshundert" — countWordOverride fix, Step 3b-iii
            ("101", "einhunderteins"),
            ("105", "einhundertfünf"),
            ("200", "zweihundert"),
            ("234", "zweihundertvierunddreissig"), // space-wall case: fully concatenated (see English at the same value below)
            ("1000", "eintausend"),                // not "einstausend" — same countWordOverride fix
            ("1500", "eintausendfünfhundert"),
        ];
        for (input, want) in cases {
            let result = normalize_word(input, Language::De, &v, &data);
            assert!(result.representable, "{input} should be representable");
            assert_eq!(result.mapped.as_deref(), Some(*want), "input {input}");
        }
    }

    #[test]
    fn german_cardinal_survives_inside_a_phrase() {
        let v = real_vocab_for(Language::De);
        let data = cardinal_data_for(Language::De);
        let result = normalize_for_forced_alignment("ich bin 23 jahre alt", Language::De, &v, &data);
        assert_eq!(result.text, "ich bin dreiundzwanzig jahre alt");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn portuguese_cardinal_generator() {
        let data = cardinal_data_for(Language::Pt);
        let v = real_vocab_for(Language::Pt);
        let cases: &[(&str, &str)] = &[
            ("0", "zero"),
            ("3", "três"),
            ("14", "quatorze"), // PT-BR variant
            ("16", "dezesseis"),
            ("17", "dezessete"),
            ("19", "dezenove"),
            ("20", "vinte"),
            ("21", "vinte e um"), // former permanent "vinte e X" wall — now representable
            ("29", "vinte e nove"),
            ("30", "trinta"),
            ("31", "trinta e um"), // former scope cap — now representable
            ("100", "cem"),
            ("101", "cento e um"),
            ("105", "cento e cinco"),
            ("200", "duzentos"),
            ("234", "duzentos e trinta e quatro"),
            ("1000", "mil"),
            ("1500", "mil quinhentos"),
            ("1000000", "um milhão"),
            ("2000000", "dois milhões"),
        ];
        for (input, want) in cases {
            let result = normalize_word(input, Language::Pt, &v, &data);
            assert!(result.representable, "{input} should be representable");
            assert_eq!(result.mapped.as_deref(), Some(*want), "input {input}");
        }
    }

    #[test]
    fn portuguese_cardinal_survives_inside_a_phrase() {
        let v = real_vocab_for(Language::Pt);
        let data = cardinal_data_for(Language::Pt);
        let result = normalize_for_forced_alignment("tenho 3 gatos", Language::Pt, &v, &data);
        assert_eq!(result.text, "tenho três gatos");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn french_cardinal_generator() {
        let data = cardinal_data_for(Language::Fr);
        let v = real_vocab_for(Language::Fr);
        let cases: &[(&str, &str)] = &[
            ("0", "zéro"),
            ("1", "un"),
            ("17", "dix-sept"), // hyphenated teen, one token in/out
            ("18", "dix-huit"),
            ("19", "dix-neuf"),
            ("20", "vingt"),
            ("21", "vingt et un"), // former permanent "vingt et un" wall — now representable
            ("22", "vingt-deux"),
            ("29", "vingt-neuf"),
            ("30", "trente"),
            ("31", "trente et un"), // former scope cap — now representable
            ("100", "cent"),       // dropsOneMultiplier: no leading "un"
            ("101", "cent un"),
            ("105", "cent cinq"),
            ("200", "deux cents"),               // exact multiple of 100 pluralizes "cent"
            ("234", "deux cent trente-quatre"),  // NOT an exact multiple: no 's' on "cent"
            ("1000", "mille"),
            ("1500", "mille cinq cents"),
            ("1000000", "un million"),
            ("2000000", "deux millions"),
        ];
        for (input, want) in cases {
            let result = normalize_word(input, Language::Fr, &v, &data);
            assert!(result.representable, "{input} should be representable");
            assert_eq!(result.mapped.as_deref(), Some(*want), "input {input}");
        }
    }

    #[test]
    fn french_cardinal_hyphenated_expansion_stays_one_word_result_not_two() {
        // The specific worry that stalled the old capped Rule 5: does one
        // hyphenated input token produce two WordResults? It does not.
        let v = real_vocab_for(Language::Fr);
        let data = cardinal_data_for(Language::Fr);
        let result = normalize_for_forced_alignment("dix-sept sont ici", Language::Fr, &v, &data);
        assert_eq!(result.words.len(), 3);
        assert_eq!(result.words[0].mapped.as_deref(), Some("dix-sept"));
    }

    #[test]
    fn french_cardinal_survives_inside_a_phrase() {
        let v = real_vocab_for(Language::Fr);
        let data = cardinal_data_for(Language::Fr);
        let result = normalize_for_forced_alignment("il a 17 ans", Language::Fr, &v, &data);
        assert_eq!(result.text, "il a dix-sept ans");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn elision_backtick_fold_and_cardinal_expansion_both_fire_in_one_phrase() {
        let v = real_vocab_for(Language::Fr);
        let data = cardinal_data_for(Language::Fr);
        let result = normalize_for_forced_alignment("j`ai 17 ans", Language::Fr, &v, &data);
        assert_eq!(result.text, "j'ai dix-sept ans");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn elision_backtick_fold_and_a_hyphenated_cardinal_both_survive_together() {
        let v = real_vocab_for(Language::Fr);
        let data = cardinal_data_for(Language::Fr);
        let result = normalize_for_forced_alignment("qu`il a 22 ans", Language::Fr, &v, &data);
        assert_eq!(result.text, "qu'il a vingt-deux ans");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn english_cardinal_generator() {
        // NEW — no FA-side cardinal expansion existed for English before
        // this step; every digit token was unconditionally dropped.
        let data = cardinal_data_for(Language::En);
        let v = real_vocab_for(Language::En);
        let cases: &[(&str, &str)] = &[
            ("0", "zero"),
            ("5", "five"),
            ("16", "sixteen"),
            ("20", "twenty"),
            ("23", "twenty-three"), // former "unaffected-language control" value under every other language's old test
            ("30", "thirty"),
            ("31", "thirty-one"),
            ("99", "ninety-nine"),
            ("100", "one hundred"),
            ("101", "one hundred one"),
            ("200", "two hundred"),
            ("234", "two hundred thirty-four"), // space-wall case (see German's single-word counterpart above)
            ("1000", "one thousand"),
            ("1500", "one thousand five hundred"),
            ("1000000", "one million"),
            ("2000000", "two million"),
        ];
        for (input, want) in cases {
            let result = normalize_word(input, Language::En, &v, &data);
            assert!(result.representable, "{input} should be representable");
            assert_eq!(result.mapped.as_deref(), Some(*want), "input {input}");
        }
    }

    #[test]
    fn english_cardinal_survives_inside_a_phrase() {
        let v = real_vocab_for(Language::En);
        let data = cardinal_data_for(Language::En);
        let result = normalize_for_forced_alignment("I turned 23 years old", Language::En, &v, &data);
        assert_eq!(result.text, "i turned twenty-three years old");
        assert!(result.words.iter().all(|w| w.representable));
    }

    #[test]
    fn negative_cardinal_decimal_and_leading_zero_stay_dropped_all_languages() {
        // Unaffected by Step 3b-iii — still out of `expand_cardinal_token`'s
        // scope regardless of language.
        for lang in [Language::En, Language::Es, Language::Fr, Language::De, Language::Pt] {
            let v = real_vocab_for(lang);
            let data = cardinal_data_for(lang);
            for input in ["2.5", "05"] {
                let result = normalize_word(input, lang, &v, &data);
                assert!(!result.representable, "{lang:?} {input} should stay dropped");
                assert!(result.reason.as_deref().unwrap().contains("digit"));
            }
        }
    }

    // -- yearReading (WS2 T3.2 Step 3b-ii's selectionPolicy, consumed here
    // for the first time) -----------------------------------------------
    //
    // en/de: the modFloorThreshold policy — n % 100 >= 10 selects the
    // "pair"/"hundertgruppe" candidate, else the "compound" (plain cardinal)
    // fallback — mirroring the matcher's (`textNormalize.ts`) own x00-x09
    // quirk on purpose. es/fr/pt: a plain "compound" string policy — always
    // the full cardinal.

    #[test]
    fn year_reading_generator() {
        let cases: &[(Language, &str, &str)] = &[
            (Language::En, "1998", "nineteen ninety-eight"), // >= threshold: "pair"
            (Language::En, "1905", "one thousand nine hundred five"), // < threshold (x00-x09 quirk): "compound"
            (Language::En, "2010", "twenty ten"),
            (Language::En, "2004", "two thousand four"),
            (Language::De, "1998", "neunzehnhundertachtundneunzig"), // >= threshold: "hundertgruppe"
            (Language::De, "1905", "eintausendneunhundertfünf"),     // < threshold: "compound"
            (Language::Es, "1998", "mil novecientos noventa y ocho"), // plain "compound" policy, always
            (Language::Fr, "1998", "mille neuf cent quatre-vingt-dix-huit"),
            (Language::Pt, "1998", "mil novecentos e noventa e oito"),
        ];
        for (lang, input, want) in cases {
            let v = real_vocab_for(*lang);
            let data = cardinal_data_for(*lang);
            let result = normalize_word(input, *lang, &v, &data);
            assert!(result.representable, "{lang:?} {input} should be representable");
            assert_eq!(result.mapped.as_deref(), Some(*want), "{lang:?} {input}");
        }
    }

    #[test]
    fn year_reading_does_not_apply_to_a_3_digit_token_even_inside_the_numeric_range() {
        // yearReading only applies to a 4-CHARACTER token (mirrors the
        // matcher's own `tok.length === 4` gate) — "998" doesn't qualify
        // even though 1998 itself is in range.
        let v = real_vocab_for(Language::En);
        let data = cardinal_data_for(Language::En);
        let result = normalize_word("998", Language::En, &v, &data);
        assert!(result.representable);
        assert_eq!(result.mapped.as_deref(), Some("nine hundred ninety-eight")); // plain cardinal, not year-pair
    }
}

// ---------------------------------------------------------------------------
// Fixture parity — proves this port is byte-identical to the live TS module
// over the shared corpus. HARD GATE, all five languages.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod fixture_parity {
    use super::*;
    use std::collections::HashMap;

    #[derive(serde::Deserialize)]
    struct FixtureFile {
        entries: Vec<FixtureEntry>,
    }

    #[derive(serde::Deserialize)]
    struct FixtureEntry {
        language: String,
        input: String,
        #[allow(dead_code)]
        note: String,
        words: Vec<FixtureWord>,
        text: String,
    }

    #[derive(serde::Deserialize)]
    struct FixtureWord {
        input: String,
        representable: bool,
        mapped: Option<String>,
        reason: Option<String>,
    }

    fn fixtures_dir() -> std::path::PathBuf {
        std::path::PathBuf::from(format!("{}/../scripts/fixtures", env!("CARGO_MANIFEST_DIR")))
    }

    fn load_fixture() -> FixtureFile {
        let path = fixtures_dir().join("fa-text-normalize-fixture.json");
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
    }

    fn load_all_vocabs() -> HashMap<Language, HashSet<char>> {
        let mut map = HashMap::new();
        for lang in [Language::En, Language::Es, Language::Fr, Language::De, Language::Pt] {
            let path = fixtures_dir().join(format!("fa-vocab-{}.json", lang.code()));
            let chars = vocab_chars_from_path(&path).unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()));
            map.insert(lang, chars);
        }
        map
    }

    fn load_all_cardinal_data() -> HashMap<Language, FaCardinalData> {
        let mut map = HashMap::new();
        for lang in [Language::En, Language::Es, Language::Fr, Language::De, Language::Pt] {
            let path = fixtures_dir().join(format!("fa-cardinal-{}.json", lang.code()));
            let data = cardinal_data_from_path(&path).unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()));
            map.insert(lang, data);
        }
        map
    }

    #[test]
    fn fixture_matches_rust_port_for_every_entry_all_five_languages() {
        let fixture = load_fixture();
        let vocabs = load_all_vocabs();
        let cardinal_data = load_all_cardinal_data();
        assert!(!fixture.entries.is_empty(), "fixture must not be empty");

        let mut seen_languages: HashSet<&str> = HashSet::new();
        let mut mismatches = Vec::new();

        for entry in &fixture.entries {
            seen_languages.insert(entry.language.as_str());
            let language = Language::from_code(&entry.language)
                .unwrap_or_else(|| panic!("fixture entry has unknown language code: {}", entry.language));
            let vocab_chars = &vocabs[&language];

            let got = normalize_for_forced_alignment(&entry.input, language, vocab_chars, &cardinal_data[&language]);

            if got.text != entry.text {
                mismatches.push(format!(
                    "input {:?} ({}): text mismatch — got {:?}, want {:?}",
                    entry.input, entry.language, got.text, entry.text
                ));
                continue;
            }
            if got.words.len() != entry.words.len() {
                mismatches.push(format!(
                    "input {:?} ({}): word count mismatch — got {}, want {}",
                    entry.input,
                    entry.language,
                    got.words.len(),
                    entry.words.len()
                ));
                continue;
            }
            for (i, (got_word, want_word)) in got.words.iter().zip(entry.words.iter()).enumerate() {
                if got_word.input != want_word.input
                    || got_word.representable != want_word.representable
                    || got_word.mapped != want_word.mapped
                    || got_word.reason != want_word.reason
                {
                    mismatches.push(format!(
                        "input {:?} ({}) word[{i}]: got {got_word:?}, want input={:?} representable={} mapped={:?} reason={:?}",
                        entry.input, entry.language, want_word.input, want_word.representable, want_word.mapped, want_word.reason
                    ));
                }
            }
        }

        assert_eq!(
            seen_languages,
            HashSet::from(["en", "es", "fr", "de", "pt"]),
            "fixture must cover all five languages"
        );

        assert!(
            mismatches.is_empty(),
            "{} mismatch(es) between Rust port and TS-generated fixture:\n{}",
            mismatches.len(),
            mismatches.join("\n")
        );
    }

    #[test]
    fn fixture_oov_case_is_genuinely_rejected_by_both_reference_and_port() {
        // Non-vacuity check for the OOV-rejection requirement: the fixture's
        // Cyrillic case must (a) exist, (b) be recorded as unrepresentable by
        // the TS reference, and (c) the vocab it was checked against must
        // truly lack that character, so a permissive Rust port can't pass by
        // accident.
        let fixture = load_fixture();
        let vocabs = load_all_vocabs();
        let cardinal_data = load_all_cardinal_data();

        let oov_entry = fixture
            .entries
            .iter()
            .find(|e| e.input.contains('п'))
            .expect("fixture must contain a genuine OOV (Cyrillic) case");

        let language = Language::from_code(&oov_entry.language).unwrap();
        assert!(
            !vocabs[&language].contains(&'п'),
            "test premise violated: the {} vocab must not contain 'п'",
            oov_entry.language
        );

        let oov_word = oov_entry.words.iter().find(|w| w.input.contains('п')).unwrap();
        assert!(!oov_word.representable, "fixture premise: TS reference must reject the OOV word");

        let got = normalize_word(&oov_word.input, language, &vocabs[&language], &cardinal_data[&language]);
        assert!(!got.representable, "Rust port must also reject the OOV word — port must not be permissive");
        assert_eq!(got.reason, oov_word.reason);
    }
}


// ---------------------------------------------------------------------------
// NFC completeness guard (WS1 Task 5 Slice D4) — closes the D3 finding that
// an out-of-table combining-mark sequence degrades SILENTLY into an
// ordinary "unrepresentable word" drop, indistinguishable from legitimate
// OOV. Proves every accented letter actually present in a shipped vocab has
// a real NFC_COMPOSE entry, and fails loudly (not silently) the moment a
// vocab is ever extended past the table.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod nfc_completeness_guard {
    use super::*;

    /// Independent ground-truth reference: real Unicode canonical (NFD)
    /// decompositions for every decomposable Latin-1 Supplement / Latin
    /// Extended-A / Latin Extended-B letter (U+00C0..U+0250), generated
    /// directly from Python's `unicodedata.normalize('NFD', ch)` over that
    /// codepoint range — NOT derived from, copied out of, or in any way
    /// coupled to `NFC_COMPOSE` above, so the two tables cannot trivially
    /// agree by construction. Deliberately far broader (230 entries) than
    /// `NFC_COMPOSE`'s current ~54: this is what makes the guard below
    /// forward-looking rather than a tautology — a vocab later extended
    /// with a not-yet-tabled accented letter (e.g. Icelandic "ý", Turkish
    /// "ğ") is still recognized as genuinely decomposable here and
    /// correctly flagged as an `NFC_COMPOSE` gap, rather than silently
    /// treated as an atomic, no-decomposition character the guard has
    /// nothing to check.
    const REFERENCE_NFD: &[(char, char, char)] = &[
    ('\u{0041}', '\u{0300}', '\u{00c0}'), // A+combining -> À
    ('\u{0041}', '\u{0301}', '\u{00c1}'), // A+combining -> Á
    ('\u{0041}', '\u{0302}', '\u{00c2}'), // A+combining -> Â
    ('\u{0041}', '\u{0303}', '\u{00c3}'), // A+combining -> Ã
    ('\u{0041}', '\u{0308}', '\u{00c4}'), // A+combining -> Ä
    ('\u{0041}', '\u{030a}', '\u{00c5}'), // A+combining -> Å
    ('\u{0043}', '\u{0327}', '\u{00c7}'), // C+combining -> Ç
    ('\u{0045}', '\u{0300}', '\u{00c8}'), // E+combining -> È
    ('\u{0045}', '\u{0301}', '\u{00c9}'), // E+combining -> É
    ('\u{0045}', '\u{0302}', '\u{00ca}'), // E+combining -> Ê
    ('\u{0045}', '\u{0308}', '\u{00cb}'), // E+combining -> Ë
    ('\u{0049}', '\u{0300}', '\u{00cc}'), // I+combining -> Ì
    ('\u{0049}', '\u{0301}', '\u{00cd}'), // I+combining -> Í
    ('\u{0049}', '\u{0302}', '\u{00ce}'), // I+combining -> Î
    ('\u{0049}', '\u{0308}', '\u{00cf}'), // I+combining -> Ï
    ('\u{004e}', '\u{0303}', '\u{00d1}'), // N+combining -> Ñ
    ('\u{004f}', '\u{0300}', '\u{00d2}'), // O+combining -> Ò
    ('\u{004f}', '\u{0301}', '\u{00d3}'), // O+combining -> Ó
    ('\u{004f}', '\u{0302}', '\u{00d4}'), // O+combining -> Ô
    ('\u{004f}', '\u{0303}', '\u{00d5}'), // O+combining -> Õ
    ('\u{004f}', '\u{0308}', '\u{00d6}'), // O+combining -> Ö
    ('\u{0055}', '\u{0300}', '\u{00d9}'), // U+combining -> Ù
    ('\u{0055}', '\u{0301}', '\u{00da}'), // U+combining -> Ú
    ('\u{0055}', '\u{0302}', '\u{00db}'), // U+combining -> Û
    ('\u{0055}', '\u{0308}', '\u{00dc}'), // U+combining -> Ü
    ('\u{0059}', '\u{0301}', '\u{00dd}'), // Y+combining -> Ý
    ('\u{0061}', '\u{0300}', '\u{00e0}'), // a+combining -> à
    ('\u{0061}', '\u{0301}', '\u{00e1}'), // a+combining -> á
    ('\u{0061}', '\u{0302}', '\u{00e2}'), // a+combining -> â
    ('\u{0061}', '\u{0303}', '\u{00e3}'), // a+combining -> ã
    ('\u{0061}', '\u{0308}', '\u{00e4}'), // a+combining -> ä
    ('\u{0061}', '\u{030a}', '\u{00e5}'), // a+combining -> å
    ('\u{0063}', '\u{0327}', '\u{00e7}'), // c+combining -> ç
    ('\u{0065}', '\u{0300}', '\u{00e8}'), // e+combining -> è
    ('\u{0065}', '\u{0301}', '\u{00e9}'), // e+combining -> é
    ('\u{0065}', '\u{0302}', '\u{00ea}'), // e+combining -> ê
    ('\u{0065}', '\u{0308}', '\u{00eb}'), // e+combining -> ë
    ('\u{0069}', '\u{0300}', '\u{00ec}'), // i+combining -> ì
    ('\u{0069}', '\u{0301}', '\u{00ed}'), // i+combining -> í
    ('\u{0069}', '\u{0302}', '\u{00ee}'), // i+combining -> î
    ('\u{0069}', '\u{0308}', '\u{00ef}'), // i+combining -> ï
    ('\u{006e}', '\u{0303}', '\u{00f1}'), // n+combining -> ñ
    ('\u{006f}', '\u{0300}', '\u{00f2}'), // o+combining -> ò
    ('\u{006f}', '\u{0301}', '\u{00f3}'), // o+combining -> ó
    ('\u{006f}', '\u{0302}', '\u{00f4}'), // o+combining -> ô
    ('\u{006f}', '\u{0303}', '\u{00f5}'), // o+combining -> õ
    ('\u{006f}', '\u{0308}', '\u{00f6}'), // o+combining -> ö
    ('\u{0075}', '\u{0300}', '\u{00f9}'), // u+combining -> ù
    ('\u{0075}', '\u{0301}', '\u{00fa}'), // u+combining -> ú
    ('\u{0075}', '\u{0302}', '\u{00fb}'), // u+combining -> û
    ('\u{0075}', '\u{0308}', '\u{00fc}'), // u+combining -> ü
    ('\u{0079}', '\u{0301}', '\u{00fd}'), // y+combining -> ý
    ('\u{0079}', '\u{0308}', '\u{00ff}'), // y+combining -> ÿ
    ('\u{0041}', '\u{0304}', '\u{0100}'), // A+combining -> Ā
    ('\u{0061}', '\u{0304}', '\u{0101}'), // a+combining -> ā
    ('\u{0041}', '\u{0306}', '\u{0102}'), // A+combining -> Ă
    ('\u{0061}', '\u{0306}', '\u{0103}'), // a+combining -> ă
    ('\u{0041}', '\u{0328}', '\u{0104}'), // A+combining -> Ą
    ('\u{0061}', '\u{0328}', '\u{0105}'), // a+combining -> ą
    ('\u{0043}', '\u{0301}', '\u{0106}'), // C+combining -> Ć
    ('\u{0063}', '\u{0301}', '\u{0107}'), // c+combining -> ć
    ('\u{0043}', '\u{0302}', '\u{0108}'), // C+combining -> Ĉ
    ('\u{0063}', '\u{0302}', '\u{0109}'), // c+combining -> ĉ
    ('\u{0043}', '\u{0307}', '\u{010a}'), // C+combining -> Ċ
    ('\u{0063}', '\u{0307}', '\u{010b}'), // c+combining -> ċ
    ('\u{0043}', '\u{030c}', '\u{010c}'), // C+combining -> Č
    ('\u{0063}', '\u{030c}', '\u{010d}'), // c+combining -> č
    ('\u{0044}', '\u{030c}', '\u{010e}'), // D+combining -> Ď
    ('\u{0064}', '\u{030c}', '\u{010f}'), // d+combining -> ď
    ('\u{0045}', '\u{0304}', '\u{0112}'), // E+combining -> Ē
    ('\u{0065}', '\u{0304}', '\u{0113}'), // e+combining -> ē
    ('\u{0045}', '\u{0306}', '\u{0114}'), // E+combining -> Ĕ
    ('\u{0065}', '\u{0306}', '\u{0115}'), // e+combining -> ĕ
    ('\u{0045}', '\u{0307}', '\u{0116}'), // E+combining -> Ė
    ('\u{0065}', '\u{0307}', '\u{0117}'), // e+combining -> ė
    ('\u{0045}', '\u{0328}', '\u{0118}'), // E+combining -> Ę
    ('\u{0065}', '\u{0328}', '\u{0119}'), // e+combining -> ę
    ('\u{0045}', '\u{030c}', '\u{011a}'), // E+combining -> Ě
    ('\u{0065}', '\u{030c}', '\u{011b}'), // e+combining -> ě
    ('\u{0047}', '\u{0302}', '\u{011c}'), // G+combining -> Ĝ
    ('\u{0067}', '\u{0302}', '\u{011d}'), // g+combining -> ĝ
    ('\u{0047}', '\u{0306}', '\u{011e}'), // G+combining -> Ğ
    ('\u{0067}', '\u{0306}', '\u{011f}'), // g+combining -> ğ
    ('\u{0047}', '\u{0307}', '\u{0120}'), // G+combining -> Ġ
    ('\u{0067}', '\u{0307}', '\u{0121}'), // g+combining -> ġ
    ('\u{0047}', '\u{0327}', '\u{0122}'), // G+combining -> Ģ
    ('\u{0067}', '\u{0327}', '\u{0123}'), // g+combining -> ģ
    ('\u{0048}', '\u{0302}', '\u{0124}'), // H+combining -> Ĥ
    ('\u{0068}', '\u{0302}', '\u{0125}'), // h+combining -> ĥ
    ('\u{0049}', '\u{0303}', '\u{0128}'), // I+combining -> Ĩ
    ('\u{0069}', '\u{0303}', '\u{0129}'), // i+combining -> ĩ
    ('\u{0049}', '\u{0304}', '\u{012a}'), // I+combining -> Ī
    ('\u{0069}', '\u{0304}', '\u{012b}'), // i+combining -> ī
    ('\u{0049}', '\u{0306}', '\u{012c}'), // I+combining -> Ĭ
    ('\u{0069}', '\u{0306}', '\u{012d}'), // i+combining -> ĭ
    ('\u{0049}', '\u{0328}', '\u{012e}'), // I+combining -> Į
    ('\u{0069}', '\u{0328}', '\u{012f}'), // i+combining -> į
    ('\u{0049}', '\u{0307}', '\u{0130}'), // I+combining -> İ
    ('\u{004a}', '\u{0302}', '\u{0134}'), // J+combining -> Ĵ
    ('\u{006a}', '\u{0302}', '\u{0135}'), // j+combining -> ĵ
    ('\u{004b}', '\u{0327}', '\u{0136}'), // K+combining -> Ķ
    ('\u{006b}', '\u{0327}', '\u{0137}'), // k+combining -> ķ
    ('\u{004c}', '\u{0301}', '\u{0139}'), // L+combining -> Ĺ
    ('\u{006c}', '\u{0301}', '\u{013a}'), // l+combining -> ĺ
    ('\u{004c}', '\u{0327}', '\u{013b}'), // L+combining -> Ļ
    ('\u{006c}', '\u{0327}', '\u{013c}'), // l+combining -> ļ
    ('\u{004c}', '\u{030c}', '\u{013d}'), // L+combining -> Ľ
    ('\u{006c}', '\u{030c}', '\u{013e}'), // l+combining -> ľ
    ('\u{004e}', '\u{0301}', '\u{0143}'), // N+combining -> Ń
    ('\u{006e}', '\u{0301}', '\u{0144}'), // n+combining -> ń
    ('\u{004e}', '\u{0327}', '\u{0145}'), // N+combining -> Ņ
    ('\u{006e}', '\u{0327}', '\u{0146}'), // n+combining -> ņ
    ('\u{004e}', '\u{030c}', '\u{0147}'), // N+combining -> Ň
    ('\u{006e}', '\u{030c}', '\u{0148}'), // n+combining -> ň
    ('\u{004f}', '\u{0304}', '\u{014c}'), // O+combining -> Ō
    ('\u{006f}', '\u{0304}', '\u{014d}'), // o+combining -> ō
    ('\u{004f}', '\u{0306}', '\u{014e}'), // O+combining -> Ŏ
    ('\u{006f}', '\u{0306}', '\u{014f}'), // o+combining -> ŏ
    ('\u{004f}', '\u{030b}', '\u{0150}'), // O+combining -> Ő
    ('\u{006f}', '\u{030b}', '\u{0151}'), // o+combining -> ő
    ('\u{0052}', '\u{0301}', '\u{0154}'), // R+combining -> Ŕ
    ('\u{0072}', '\u{0301}', '\u{0155}'), // r+combining -> ŕ
    ('\u{0052}', '\u{0327}', '\u{0156}'), // R+combining -> Ŗ
    ('\u{0072}', '\u{0327}', '\u{0157}'), // r+combining -> ŗ
    ('\u{0052}', '\u{030c}', '\u{0158}'), // R+combining -> Ř
    ('\u{0072}', '\u{030c}', '\u{0159}'), // r+combining -> ř
    ('\u{0053}', '\u{0301}', '\u{015a}'), // S+combining -> Ś
    ('\u{0073}', '\u{0301}', '\u{015b}'), // s+combining -> ś
    ('\u{0053}', '\u{0302}', '\u{015c}'), // S+combining -> Ŝ
    ('\u{0073}', '\u{0302}', '\u{015d}'), // s+combining -> ŝ
    ('\u{0053}', '\u{0327}', '\u{015e}'), // S+combining -> Ş
    ('\u{0073}', '\u{0327}', '\u{015f}'), // s+combining -> ş
    ('\u{0053}', '\u{030c}', '\u{0160}'), // S+combining -> Š
    ('\u{0073}', '\u{030c}', '\u{0161}'), // s+combining -> š
    ('\u{0054}', '\u{0327}', '\u{0162}'), // T+combining -> Ţ
    ('\u{0074}', '\u{0327}', '\u{0163}'), // t+combining -> ţ
    ('\u{0054}', '\u{030c}', '\u{0164}'), // T+combining -> Ť
    ('\u{0074}', '\u{030c}', '\u{0165}'), // t+combining -> ť
    ('\u{0055}', '\u{0303}', '\u{0168}'), // U+combining -> Ũ
    ('\u{0075}', '\u{0303}', '\u{0169}'), // u+combining -> ũ
    ('\u{0055}', '\u{0304}', '\u{016a}'), // U+combining -> Ū
    ('\u{0075}', '\u{0304}', '\u{016b}'), // u+combining -> ū
    ('\u{0055}', '\u{0306}', '\u{016c}'), // U+combining -> Ŭ
    ('\u{0075}', '\u{0306}', '\u{016d}'), // u+combining -> ŭ
    ('\u{0055}', '\u{030a}', '\u{016e}'), // U+combining -> Ů
    ('\u{0075}', '\u{030a}', '\u{016f}'), // u+combining -> ů
    ('\u{0055}', '\u{030b}', '\u{0170}'), // U+combining -> Ű
    ('\u{0075}', '\u{030b}', '\u{0171}'), // u+combining -> ű
    ('\u{0055}', '\u{0328}', '\u{0172}'), // U+combining -> Ų
    ('\u{0075}', '\u{0328}', '\u{0173}'), // u+combining -> ų
    ('\u{0057}', '\u{0302}', '\u{0174}'), // W+combining -> Ŵ
    ('\u{0077}', '\u{0302}', '\u{0175}'), // w+combining -> ŵ
    ('\u{0059}', '\u{0302}', '\u{0176}'), // Y+combining -> Ŷ
    ('\u{0079}', '\u{0302}', '\u{0177}'), // y+combining -> ŷ
    ('\u{0059}', '\u{0308}', '\u{0178}'), // Y+combining -> Ÿ
    ('\u{005a}', '\u{0301}', '\u{0179}'), // Z+combining -> Ź
    ('\u{007a}', '\u{0301}', '\u{017a}'), // z+combining -> ź
    ('\u{005a}', '\u{0307}', '\u{017b}'), // Z+combining -> Ż
    ('\u{007a}', '\u{0307}', '\u{017c}'), // z+combining -> ż
    ('\u{005a}', '\u{030c}', '\u{017d}'), // Z+combining -> Ž
    ('\u{007a}', '\u{030c}', '\u{017e}'), // z+combining -> ž
    ('\u{004f}', '\u{031b}', '\u{01a0}'), // O+combining -> Ơ
    ('\u{006f}', '\u{031b}', '\u{01a1}'), // o+combining -> ơ
    ('\u{0055}', '\u{031b}', '\u{01af}'), // U+combining -> Ư
    ('\u{0075}', '\u{031b}', '\u{01b0}'), // u+combining -> ư
    ('\u{0041}', '\u{030c}', '\u{01cd}'), // A+combining -> Ǎ
    ('\u{0061}', '\u{030c}', '\u{01ce}'), // a+combining -> ǎ
    ('\u{0049}', '\u{030c}', '\u{01cf}'), // I+combining -> Ǐ
    ('\u{0069}', '\u{030c}', '\u{01d0}'), // i+combining -> ǐ
    ('\u{004f}', '\u{030c}', '\u{01d1}'), // O+combining -> Ǒ
    ('\u{006f}', '\u{030c}', '\u{01d2}'), // o+combining -> ǒ
    ('\u{0055}', '\u{030c}', '\u{01d3}'), // U+combining -> Ǔ
    ('\u{0075}', '\u{030c}', '\u{01d4}'), // u+combining -> ǔ
    ('\u{00c6}', '\u{0304}', '\u{01e2}'), // Æ+combining -> Ǣ
    ('\u{00e6}', '\u{0304}', '\u{01e3}'), // æ+combining -> ǣ
    ('\u{0047}', '\u{030c}', '\u{01e6}'), // G+combining -> Ǧ
    ('\u{0067}', '\u{030c}', '\u{01e7}'), // g+combining -> ǧ
    ('\u{004b}', '\u{030c}', '\u{01e8}'), // K+combining -> Ǩ
    ('\u{006b}', '\u{030c}', '\u{01e9}'), // k+combining -> ǩ
    ('\u{004f}', '\u{0328}', '\u{01ea}'), // O+combining -> Ǫ
    ('\u{006f}', '\u{0328}', '\u{01eb}'), // o+combining -> ǫ
    ('\u{01b7}', '\u{030c}', '\u{01ee}'), // Ʒ+combining -> Ǯ
    ('\u{0292}', '\u{030c}', '\u{01ef}'), // ʒ+combining -> ǯ
    ('\u{006a}', '\u{030c}', '\u{01f0}'), // j+combining -> ǰ
    ('\u{0047}', '\u{0301}', '\u{01f4}'), // G+combining -> Ǵ
    ('\u{0067}', '\u{0301}', '\u{01f5}'), // g+combining -> ǵ
    ('\u{004e}', '\u{0300}', '\u{01f8}'), // N+combining -> Ǹ
    ('\u{006e}', '\u{0300}', '\u{01f9}'), // n+combining -> ǹ
    ('\u{00c6}', '\u{0301}', '\u{01fc}'), // Æ+combining -> Ǽ
    ('\u{00e6}', '\u{0301}', '\u{01fd}'), // æ+combining -> ǽ
    ('\u{00d8}', '\u{0301}', '\u{01fe}'), // Ø+combining -> Ǿ
    ('\u{00f8}', '\u{0301}', '\u{01ff}'), // ø+combining -> ǿ
    ('\u{0041}', '\u{030f}', '\u{0200}'), // A+combining -> Ȁ
    ('\u{0061}', '\u{030f}', '\u{0201}'), // a+combining -> ȁ
    ('\u{0041}', '\u{0311}', '\u{0202}'), // A+combining -> Ȃ
    ('\u{0061}', '\u{0311}', '\u{0203}'), // a+combining -> ȃ
    ('\u{0045}', '\u{030f}', '\u{0204}'), // E+combining -> Ȅ
    ('\u{0065}', '\u{030f}', '\u{0205}'), // e+combining -> ȅ
    ('\u{0045}', '\u{0311}', '\u{0206}'), // E+combining -> Ȇ
    ('\u{0065}', '\u{0311}', '\u{0207}'), // e+combining -> ȇ
    ('\u{0049}', '\u{030f}', '\u{0208}'), // I+combining -> Ȉ
    ('\u{0069}', '\u{030f}', '\u{0209}'), // i+combining -> ȉ
    ('\u{0049}', '\u{0311}', '\u{020a}'), // I+combining -> Ȋ
    ('\u{0069}', '\u{0311}', '\u{020b}'), // i+combining -> ȋ
    ('\u{004f}', '\u{030f}', '\u{020c}'), // O+combining -> Ȍ
    ('\u{006f}', '\u{030f}', '\u{020d}'), // o+combining -> ȍ
    ('\u{004f}', '\u{0311}', '\u{020e}'), // O+combining -> Ȏ
    ('\u{006f}', '\u{0311}', '\u{020f}'), // o+combining -> ȏ
    ('\u{0052}', '\u{030f}', '\u{0210}'), // R+combining -> Ȑ
    ('\u{0072}', '\u{030f}', '\u{0211}'), // r+combining -> ȑ
    ('\u{0052}', '\u{0311}', '\u{0212}'), // R+combining -> Ȓ
    ('\u{0072}', '\u{0311}', '\u{0213}'), // r+combining -> ȓ
    ('\u{0055}', '\u{030f}', '\u{0214}'), // U+combining -> Ȕ
    ('\u{0075}', '\u{030f}', '\u{0215}'), // u+combining -> ȕ
    ('\u{0055}', '\u{0311}', '\u{0216}'), // U+combining -> Ȗ
    ('\u{0075}', '\u{0311}', '\u{0217}'), // u+combining -> ȗ
    ('\u{0053}', '\u{0326}', '\u{0218}'), // S+combining -> Ș
    ('\u{0073}', '\u{0326}', '\u{0219}'), // s+combining -> ș
    ('\u{0054}', '\u{0326}', '\u{021a}'), // T+combining -> Ț
    ('\u{0074}', '\u{0326}', '\u{021b}'), // t+combining -> ț
    ('\u{0048}', '\u{030c}', '\u{021e}'), // H+combining -> Ȟ
    ('\u{0068}', '\u{030c}', '\u{021f}'), // h+combining -> ȟ
    ('\u{0041}', '\u{0307}', '\u{0226}'), // A+combining -> Ȧ
    ('\u{0061}', '\u{0307}', '\u{0227}'), // a+combining -> ȧ
    ('\u{0045}', '\u{0327}', '\u{0228}'), // E+combining -> Ȩ
    ('\u{0065}', '\u{0327}', '\u{0229}'), // e+combining -> ȩ
    ('\u{004f}', '\u{0307}', '\u{022e}'), // O+combining -> Ȯ
    ('\u{006f}', '\u{0307}', '\u{022f}'), // o+combining -> ȯ
    ('\u{0059}', '\u{0304}', '\u{0232}'), // Y+combining -> Ȳ
    ('\u{0079}', '\u{0304}', '\u{0233}'), // y+combining -> ȳ

    ];

    /// Looks up `ch`'s canonical decomposition in the independent
    /// [`REFERENCE_NFD`] table above (NOT in `NFC_COMPOSE`). `None` means
    /// either `ch` is ASCII/has no canonical decomposition (e.g. "\u{0153}"
    /// / oe-ligature, confirmed atomic via `unicodedata.normalize`) or falls
    /// outside this table's deliberately-generous U+00C0..U+0250 scan range.
    fn reference_decompose(ch: char) -> Option<(char, char)> {
        REFERENCE_NFD.iter().find(|&&(_, _, precomposed)| precomposed == ch).map(|&(base, mark, _)| (base, mark))
    }

    fn fixtures_dir() -> std::path::PathBuf {
        std::path::PathBuf::from(format!("{}/../scripts/fixtures", env!("CARGO_MANIFEST_DIR")))
    }

    #[test]
    fn every_shipped_vocab_char_with_a_real_decomposition_is_covered_by_nfc_compose() {
        let mut uncovered = Vec::new();
        let mut checked = 0usize;

        for lang in ["en", "es", "fr", "de", "pt"] {
            let path = fixtures_dir().join(format!("fa-vocab-{lang}.json"));
            let chars = vocab_chars_from_path(&path).unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()));

            for &ch in &chars {
                if let Some((base, mark)) = reference_decompose(ch) {
                    checked += 1;
                    if compose_pair(base, mark) != Some(ch) {
                        uncovered.push(format!(
                            "{lang} vocab char {ch:?} (U+{:04X}) has a real NFD decomposition (base \
                             {base:?} U+{:04X} + combining mark U+{:04X}) not present in NFC_COMPOSE",
                            ch as u32, base as u32, mark as u32
                        ));
                    }
                }
            }
        }

        // Non-vacuity: this guard must have actually exercised at least one
        // real decomposable character across the five vocabs, or "0
        // uncovered" would be a meaningless pass (nothing was checked, not
        // "everything checked out"). Verified additionally by hand per the
        // task's own non-vacuity requirement: temporarily deleting one
        // NFC_COMPOSE entry (e.g. the `('e', '\u{0301}', 'é')` row) makes
        // this test fail with exactly one uncovered-char message naming that
        // pair, confirming the guard is live, not tautological.
        assert!(
            checked > 0,
            "guard must check at least one real decomposable vocab character — 0 checked would \
             make an empty `uncovered` list vacuously true"
        );

        assert!(
            uncovered.is_empty(),
            "{} shipped vocab char(s) have a real NFD decomposition NOT covered by NFC_COMPOSE — \
             extend NFC_COMPOSE with the missing base/mark/precomposed row(s):\n{}",
            uncovered.len(),
            uncovered.join("\n")
        );
    }
}
