#!/usr/bin/env python3
"""
phase4-restore-replay-inputs.py — Step Y (2026-08-07).

Regenerates the two input artifacts `scripts/phase4-handoff-replay-sync.test.ts`
(the Step M golden-baseline replay harness) needs, into a DURABLE, gitignored
location under the repo — never `/tmp`, which macOS purges and which has now
cost this programme four separate artifact losses (K8, see
docs/sync-pipeline-v2-plan.md Part K).

    .work-phase4/replay/<project>/transcript_tokens.json
    .work-phase4/replay/<project>/silences_app.json
    .work-phase4/replay/<project>/audio_16k.wav        (intermediate)

Both are regenerated from sources that are COMMITTED to this repo or are the
corpus audio itself — no whisper-cli run is required, and none should be
substituted for this path:

  * transcript_tokens.json comes from `scripts/fixtures/{V6,173,Spanish}-Smear-Phase2a.csv`
    (the Phase 2a transcript-inspector exports, committed) via the committed
    `scripts/extract-full-transcript.py`. This is the SAME derivation the
    original `/tmp/phase3/*_raw_transcript*.json` files came from, so the
    result is the same array Step M actually read — NOT a fresh transcription.
    A fresh whisper run would produce the PRE-filterMalformedTokens array
    (4556/2082/399 tokens), a different input from what Step M consumed
    (3989/1836/363, already filtered by the inspector export), and would
    therefore not reproduce the baseline faithfully.

  * silences_app.json is regenerated by the committed
    `scripts/phase4-handoff-app-silence.py` (the line-for-line Python port of
    silenceDetector.ts's RMS scan) against a fresh 16 kHz mono transcode of the
    corpus audio, made with the bundled ffmpeg sidecar — the same chain Step M
    used.

Every regenerated artifact is then verified, value for value, against the
committed Step M outputs it must reproduce (`scripts/fixtures/phase4-baseline-*-words.csv`
and `scripts/fixtures/phase4-baseline-*-silences.csv`). A mismatch is a hard failure here,
before the replay harness ever runs — so a silently-wrong restoration cannot be
mistaken for a real pipeline change downstream.

Usage:
    python3 scripts/phase4-restore-replay-inputs.py            # regenerate + verify
    python3 scripts/phase4-restore-replay-inputs.py --verify   # verify only, no regeneration
"""
import argparse
import csv
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WORKROOT = REPO / ".work-phase4" / "replay"
CORPUS = Path("/Users/mohtashim/Downloads/All Projects Test Data")
FFMPEG = REPO / "src-tauri" / "binaries" / "ffmpeg-x86_64-apple-darwin"

PROJECTS = [
    {
        "key": "v6",
        "smear_csv": REPO / "scripts" / "fixtures" / "V6-Smear-Phase2a.csv",
        "audio": CORPUS / "V6 Natural Long Pause Segs" / "6.m4a",
        "expect_tokens": 3989,
        "expect_silences": 547,
    },
    {
        "key": "173",
        "smear_csv": REPO / "scripts" / "fixtures" / "173-Smear-Phase2a.csv",
        "audio": CORPUS / "173 Segs Project" / "voiceover.m4a",
        "expect_tokens": 1836,
        "expect_silences": 239,
    },
    {
        "key": "spanish",
        "smear_csv": REPO / "scripts" / "fixtures" / "Spanish-Smear-Phase2a.csv",
        "audio": CORPUS / "Spanish Project" / "Spanish VOiceover.m4a",
        "expect_tokens": 363,
        "expect_silences": 27,
    },
]

TOL = 1e-9


def run(cmd: list) -> None:
    result = subprocess.run([str(c) for c in cmd], capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(
            f"command failed ({result.returncode}): {' '.join(str(c) for c in cmd)}\n"
            f"{result.stderr[-2000:]}"
        )


def regenerate(p: dict) -> None:
    outdir = WORKROOT / p["key"]
    outdir.mkdir(parents=True, exist_ok=True)

    if not p["smear_csv"].exists():
        raise SystemExit(f"missing committed source: {p['smear_csv']}")
    run([sys.executable, REPO / "scripts" / "extract-full-transcript.py",
         "--csv", p["smear_csv"], "--out", outdir / "transcript_tokens.json"])

    if not p["audio"].exists():
        raise SystemExit(
            f"missing corpus audio: {p['audio']}\n"
            "The corpus lives outside the repo (docs/sync-pipeline-v2-plan.md Part D.0). "
            "Restore it, or run with --verify to check already-regenerated artifacts."
        )
    if not FFMPEG.exists():
        raise SystemExit(f"missing ffmpeg sidecar: {FFMPEG} (gitignored; see src-tauri/binaries/README.md)")
    wav = outdir / "audio_16k.wav"
    run([FFMPEG, "-hide_banner", "-y", "-i", p["audio"], "-ar", "16000", "-ac", "1", wav])
    run([sys.executable, REPO / "scripts" / "phase4-handoff-app-silence.py",
         "--wav", wav, "--out", outdir / "silences_app.json"])


def verify(p: dict) -> list:
    """Value-for-value check against the committed Step M outputs. Returns failures."""
    failures = []
    outdir = WORKROOT / p["key"]

    tok_path = outdir / "transcript_tokens.json"
    if not tok_path.exists():
        return [f"{p['key']}: {tok_path} does not exist"]
    tokens = json.loads(tok_path.read_text())
    words_csv = list(csv.DictReader(
        (REPO / "scripts" / "fixtures" / f"phase4-baseline-{p['key']}-words.csv").open()))
    if len(tokens) != p["expect_tokens"] or len(tokens) != len(words_csv):
        failures.append(
            f"{p['key']}: token count {len(tokens)}, expected {p['expect_tokens']} "
            f"/ committed baseline has {len(words_csv)}")
    else:
        bad = [i for i, (t, r) in enumerate(zip(tokens, words_csv))
               if t["text"] != r["text"]
               or abs(t["start"] - float(r["startSec"])) > TOL
               or abs(t["end"] - float(r["endSec"])) > TOL]
        if bad:
            failures.append(f"{p['key']}: {len(bad)} token(s) differ from the committed "
                            f"baseline, first at index {bad[0]}")

    sil_path = outdir / "silences_app.json"
    if not sil_path.exists():
        return failures + [f"{p['key']}: {sil_path} does not exist"]
    silences = json.loads(sil_path.read_text())["silences"]
    sil_csv = list(csv.DictReader(
        (REPO / "scripts" / "fixtures" / f"phase4-baseline-{p['key']}-silences.csv").open()))
    if len(silences) != p["expect_silences"] or len(silences) != len(sil_csv):
        failures.append(
            f"{p['key']}: silence count {len(silences)}, expected {p['expect_silences']} "
            f"/ committed baseline has {len(sil_csv)}")
    else:
        bad = [i for i, (s, r) in enumerate(zip(silences, sil_csv))
               if abs(s["startSec"] - float(r["startSec"])) > TOL
               or abs(s["endSec"] - float(r["endSec"])) > TOL]
        if bad:
            failures.append(f"{p['key']}: {len(bad)} silence interval(s) differ from the "
                            f"committed baseline, first at index {bad[0]}")

    return failures


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--verify", action="store_true",
                    help="verify already-regenerated artifacts without regenerating them")
    args = ap.parse_args()

    all_failures = []
    for p in PROJECTS:
        if not args.verify:
            print(f"[restore] regenerating {p['key']} ...")
            regenerate(p)
        fails = verify(p)
        if fails:
            all_failures.extend(fails)
            for f in fails:
                print(f"[restore] FAIL  {f}")
        else:
            print(f"[restore] OK    {p['key']}: {p['expect_tokens']} tokens, "
                  f"{p['expect_silences']} silences — value-for-value identical to "
                  f"scripts/fixtures/phase4-baseline-{p['key']}-{{words,silences}}.csv")

    if all_failures:
        print(f"\n[restore] {len(all_failures)} verification failure(s). The restored inputs "
              "do NOT reproduce the committed Step M baseline — do not run the replay "
              "harness against them, and do not re-baseline to whatever they produce.")
        return 1

    print(f"\n[restore] all 3 projects verified against the committed Step M baseline.\n"
          f"[restore] artifacts: {WORKROOT} (gitignored, durable — not /tmp)\n"
          f"[restore] next: npx vitest run scripts/phase4-handoff-replay-sync.test.ts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
