// ---------------------------------------------------------------------------
// Dev-only forced-alignment invocation path (WS1 Task 5 Slice D10).
//
// NOT reachable from any UI control — no button, no menu item, no Settings
// toggle references this command. The only caller is `src/App.tsx`'s
// DEV-gated `window.__faDevAlign` global (mirrors `__transcriptInspector`'s
// own precedent: a `import.meta.env.DEV`-gated `useEffect` exposing a
// console-invokable function, never wired into any component's render
// output), invoked from the devtools console.
//
// Exists because `fa_align` (`fa.rs`) takes a filesystem path to an
// already-16kHz-mono-WAV file — by design (its own doc comment: "reuses
// whatever the caller already has on disk"), it does not itself transcode
// anything. In production, no caller currently produces a DURABLE WAV at a
// path `fa_align` could consume: `whisper.rs::transcode_to_wav` produces one
// but `whisper_transcribe` deletes it (`fs::remove_dir_all`) the moment
// whisper-cli exits — confirmed by reading that function before writing this
// one. This command closes that gap for the dev path by obtaining a durable
// WAV via `fa::ensure_durable_wav` (WS1 Task 5 Slice D25 A1 — previously a
// throwaway per-call WAV via `transcode_to_wav` directly, see `fa_align_dev`'s
// own doc comment for why that changed) and then delegating to the REAL,
// unmodified `fa_align` — so what this slice actually exercises is production
// `fa_align` (and, as of D25, production `ensure_durable_wav`) itself, not a
// reimplementation of either.
// ---------------------------------------------------------------------------

use crate::fa::{fa_model_path, FaChunkInput, FaError, FaErrorKind, FaEvent, FaModelCache, FaState};
use std::fs;
use std::path::Path;
use tauri::ipc::Channel;

/// Embedded verbatim (WS1 Task 5 Slice D2's `fa-onnx-manifest.json`,
/// generated by `scripts/export-fa-onnx.py`) — same `include_str!`
/// convention `fa_onnx.rs::vocab_json_for` already uses for the per-language
/// vocab fixtures. The manifest's own `_provenance.note` says "Consumed by
/// Step T (deferred)" — Step T (the on-demand downloader) is still deferred;
/// this is a DIFFERENT consumer (a manual pre-use integrity check for a
/// model an operator placed by hand per the R-D manual-placement fallback),
/// not Step T itself.
const FA_ONNX_MANIFEST_JSON: &str = include_str!("../../scripts/fixtures/fa-onnx-manifest.json");

fn manifest_sha256_for(language: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(FA_ONNX_MANIFEST_JSON).ok()?;
    v["models"][language]["sha256"].as_str().map(|s| s.to_string())
}

/// The manifest's own recorded `byteSize` for `language` — the input to the
/// WS1 Session G size precheck below. Already present in every entry of
/// `fa-onnx-manifest.json` (written by `scripts/export-fa-onnx.py` alongside
/// the sha256), so this costs nothing new to record and is an EXACT expected
/// value, not a heuristic bound.
pub(crate) fn manifest_byte_size_for(language: &str) -> Option<u64> {
    let v: serde_json::Value = serde_json::from_str(FA_ONNX_MANIFEST_JSON).ok()?;
    v["models"][language]["byteSize"].as_u64()
}

/// Identity of a file as cheaply as the filesystem can state it: path, byte
/// length, and mtime. The SAME technique `fa.rs::source_identity_key`
/// already uses for the durable-WAV cache (`name|size|mtime`) and that
/// `syncEngine.ts::getFileIdentity` uses on the TS side — reused rather than
/// invented, and carrying the same known limitation (a replacement that
/// preserves both size and mtime is not detected).
type ModelIdentity = (std::path::PathBuf, u64, Option<std::time::SystemTime>);

/// Memoized full-file digests, keyed on `ModelIdentity`.
///
/// IN-PROCESS ONLY, deliberately. It is never persisted, so every app start
/// re-hashes the model in full and no stale or poisoned entry can outlive a
/// restart. What it removes is the per-CALL tax: before this, every single
/// Apply Sync re-hashed ~1.26 GiB (measured ~5.25s release / ~77.43s debug,
/// WS1 Session F), model healthy or not.
///
/// It stores the COMPUTED DIGEST, not a boolean verdict — the equality
/// check against the manifest still runs on every call, so a cache hit can
/// never turn a mismatched model into an accepted one. It also memoizes a
/// BAD digest, which is what brings the repeat same-size-corruption case
/// under budget.
fn verified_digest_cache() -> &'static std::sync::Mutex<std::collections::HashMap<ModelIdentity, String>> {
    static CACHE: std::sync::OnceLock<
        std::sync::Mutex<std::collections::HashMap<ModelIdentity, String>>,
    > = std::sync::OnceLock::new();
    CACHE.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

/// Test-only: empties the memo so a test can measure a cold call.
#[cfg(test)]
pub(crate) fn reset_verified_digest_cache_for_tests() {
    if let Ok(mut m) = verified_digest_cache().lock() {
        m.clear();
    }
}

/// The digest for `path`, from `verified_digest_cache` if a hash for this
/// EXACT file identity (path + size + mtime) is already there, computed and
/// cached otherwise. Deliberately NOT refactored to share code with
/// `verify_model_manifest` (below), which inlines the identical cache
/// check-then-hash-then-insert sequence — that function sits on a heavily
/// tested, sensitive verification path and touching its internals for this
/// wasn't worth the risk. The two cannot disagree regardless: both read and
/// write the SAME `verified_digest_cache`, so a value either one caches is
/// found by the other — consistency comes from the shared cache, not from
/// shared code.
///
/// WS2 T4.8: this is the function that makes `models::fa_model_download`'s
/// post-success sidecar write free. `verify_model_manifest` runs during
/// every download's finalize step and populates this cache for the `.part`
/// path at that moment; calling this again immediately after — same path,
/// same size, same mtime, nothing has touched the file since — is a
/// guaranteed cache hit: a `stat`, not a second ~1.2 GiB read. Before this
/// existed, `fa_model_download` hashed the file a second time under a
/// different name to get a digest for the sidecar, and that second read,
/// competing with macOS Spotlight indexing the file it had just finished
/// writing, was MEASURED hanging past 90 seconds on the operator's machine.
pub(crate) fn digest_for_sidecar(path: &Path) -> std::io::Result<String> {
    let meta = std::fs::metadata(path)?;
    let identity: ModelIdentity = (path.to_path_buf(), meta.len(), meta.modified().ok());
    if let Some(digest) = verified_digest_cache().lock().ok().and_then(|m| m.get(&identity).cloned()) {
        return Ok(digest);
    }
    let digest = crate::sha256::hash_file(path)?;
    if let Ok(mut m) = verified_digest_cache().lock() {
        m.insert(identity, digest.clone());
    }
    Ok(digest)
}

/// Whether `verified_digest_cache` already holds a digest for `path`'s EXACT
/// current identity — i.e. whether the very next [`verify_model_manifest`]
/// call for it would be a map lookup rather than a full ~1.26 GiB stream
/// hash (WS3 fa-perf-foundation).
///
/// A read-only PROBE, called immediately before `verify_model_manifest` so
/// the production timing surface can label that stage `manifestDigestCacheHit
/// true/false`. Deliberately a separate function rather than a new return
/// value on `verify_model_manifest` itself: that function's own doc comment
/// records the standing decision not to touch its internals for
/// instrumentation ("sits on a heavily tested, sensitive verification path"),
/// and this probe honours it — it hashes nothing, decides nothing, and cannot
/// change what `verify_model_manifest` then does.
///
/// A `false` here can only ever UNDER-report a hit (if something populated
/// the memo between this probe and the call), never over-report one: the
/// probe runs first, and nothing removes entries from the memo except
/// `reset_verified_digest_cache_for_tests`.
pub(crate) fn digest_is_memoized(path: &Path) -> bool {
    let Ok(meta) = std::fs::metadata(path) else { return false };
    let identity: ModelIdentity = (path.to_path_buf(), meta.len(), meta.modified().ok());
    verified_digest_cache().lock().map(|m| m.contains_key(&identity)).unwrap_or(false)
}

/// Hashes `path` and compares against the committed manifest's recorded
/// SHA-256 for `language`. Never panics — a missing manifest entry, an I/O
/// failure, and a genuine hash mismatch are all reported as a typed
/// `FaError` (`ModelHashMismatch`), not a crash. The mismatch case is the
/// real integrity check this function exists for: a `model.onnx` placed by
/// hand could be truncated, corrupted, or simply the wrong file.
///
/// WS1 SESSION G — FAIL-CLEAN BUDGET. Two cheap steps run BEFORE the full
/// ~1.26 GiB stream-hash, neither of which weakens the good case (a healthy
/// model is still hashed in full, and still compared in full):
///
///   1. SIZE PRECHECK against the manifest's own `byteSize`. A truncated,
///      empty, or simply wrong file is rejected from one `stat` — the
///      common real corruption (an interrupted download, the wrong file
///      placed by hand). Budget tier A: under 50 ms including the first
///      call. It does NOT accelerate a same-size byte flip, and is not
///      claimed to: that file still reaches the hash below.
///   2. DIGEST MEMO keyed on (path, size, mtime), in-process only. The
///      first call for a given file identity pays the full hash exactly
///      once; every later call in the same process is a map lookup. This
///      is what removes the per-Apply-Sync tax on the HEALTHY path (tier C)
///      and brings the repeat same-size-corruption case (tier B) under
///      budget. The comparison against the manifest still runs on every
///      call — the memo caches the digest, never the verdict.
pub(crate) fn verify_model_manifest(path: &Path, language: &str) -> Result<(), FaError> {
    let expected = manifest_sha256_for(language).ok_or_else(|| FaError {
        kind: FaErrorKind::ModelHashMismatch,
        message: format!("no manifest entry for language \"{language}\" in fa-onnx-manifest.json"),
    })?;

    // One `stat`, reused by both the size precheck and the memo key.
    let meta = std::fs::metadata(path).map_err(|e| FaError {
        kind: FaErrorKind::ModelHashMismatch,
        message: format!("failed to stat model at {}: {e}", path.display()),
    })?;
    let actual_size = meta.len();

    if let Some(expected_size) = manifest_byte_size_for(language) {
        if actual_size != expected_size {
            return Err(FaError {
                kind: FaErrorKind::ModelHashMismatch,
                message: format!(
                    "model at {} is {actual_size} bytes but the committed manifest for \
                     \"{language}\" records {expected_size} — wrong or truncated file. \
                     Re-download/re-export the model; do not trust a mismatched file.",
                    path.display()
                ),
            });
        }
    }

    let identity: ModelIdentity = (path.to_path_buf(), actual_size, meta.modified().ok());
    let cached = verified_digest_cache()
        .lock()
        .ok()
        .and_then(|m| m.get(&identity).cloned());

    let actual = match cached {
        Some(digest) => digest,
        None => {
            let digest = crate::sha256::hash_file(path).map_err(|e| FaError {
                kind: FaErrorKind::ModelHashMismatch,
                message: format!("failed to hash model at {}: {e}", path.display()),
            })?;
            if let Ok(mut m) = verified_digest_cache().lock() {
                m.insert(identity, digest.clone());
            }
            digest
        }
    };

    if actual != expected {
        return Err(FaError {
            kind: FaErrorKind::ModelHashMismatch,
            message: format!(
                "model at {} does not match the committed manifest for \"{language}\" — expected \
                 sha256 {expected}, got {actual}. Re-download/re-export the model; do not trust a \
                 mismatched file.",
                path.display()
            ),
        });
    }
    Ok(())
}

/// A reasonable temp filename extension from the caller-supplied hint.
/// `whisper.rs::transcode_to_wav` (ffmpeg) probes container format from the
/// file's actual content, not its extension, so an unrecognized hint still
/// works correctly — this only affects the temp filename's cosmetics.
fn extension_for(hint: &str) -> &'static str {
    match hint {
        "wav" | "audio/wav" | "audio/wave" | "audio/x-wav" => "wav",
        "mp3" | "audio/mpeg" | "audio/mp3" => "mp3",
        "ogg" | "audio/ogg" => "ogg",
        "flac" | "audio/flac" => "flac",
        "m4a" | "audio/mp4" | "audio/x-m4a" | "audio/aac" => "m4a",
        "aiff" | "audio/aiff" => "aiff",
        "webm" | "audio/webm" => "webm",
        _ => "bin",
    }
}

/// Raw-binary staging command for the `input_path` argument `fa_align_dev`
/// and `fa_align_production` now take.
///
/// Writes the invoke request's raw body bytes to a content-addressed
/// (SHA-256 of the bytes) path under `cache_dir_name` (a caller-owned
/// namespace, carried as the `cache-dir` request header, so a devtools call
/// and a real Apply-Sync call against the same audio content can never
/// collide on the same path — the two namespaces `fa_align_dev` and
/// `fa_align_production` each used to pass down to `resolve_wav_and_align`
/// before this command existed). `ext-hint` (optional; same values
/// `extension_for` below already accepts) picks the written file's
/// extension.
///
/// Content-addressing, not per-call/uuid'd, for the same reason
/// `resolve_wav_and_align`'s old inline version of this write was
/// content-addressed: `ensure_durable_wav`'s cache key is the SOURCE file's
/// own identity (name|size|mtime — `fa.rs::source_identity_key`), so a fresh
/// uuid'd temp file on every call would give every invocation of the SAME
/// clip a fresh mtime and defeat the durable cache before it ever got a
/// chance to hit.
///
/// Unlike the `audio_b64` shape this replaces, the payload is NOT
/// base64/JSON-encoded — the frontend passes a `Uint8Array` as the invoke
/// body (Tauri v2 raw request body). This removes the base64 encode (JS) +
/// inflated-string IPC transfer + base64 decode (Rust) that `ffmpeg.rs`'s
/// `ffmpeg_write_file_raw` doc comment already names as the cost this shape
/// avoids on the export path — applied here to a whole voiceover file
/// (potentially hundreds of MB uncompressed) instead of one export frame,
/// where the base64+JSON round trip's ~5-8x peak memory multiplication
/// across the JS heap and the WKWebView IPC bridge is far more likely to
/// matter.
/// How many staging records to retain. `fa_stage_audio_raw` and
/// `fa_align_production` are two SEPARATE IPC commands — the frontend calls
/// the first, gets a path back, and passes it to the second — so the staging
/// duration cannot be reported on the alignment run's own `Channel<FaEvent>`
/// unless it is parked somewhere in between. This is that somewhere.
///
/// Bounded, and small on purpose: a record is claimed (and removed) by the
/// alignment run that consumes its path, so in the normal flow at most one is
/// live at a time. The cap exists for the abnormal flow — a caller that
/// stages audio and then never aligns it leaks one record, and without a cap
/// a long-running process could accumulate them without limit. Eight is
/// generous headroom over the one the normal flow needs, and an entry evicted
/// because it aged out reports `stagingMs: null` (unknown), never a wrong
/// number.
const STAGING_RECORD_CAPACITY: usize = 8;

fn staging_durations() -> &'static std::sync::Mutex<std::collections::VecDeque<(std::path::PathBuf, u64)>> {
    static RECORDS: std::sync::OnceLock<
        std::sync::Mutex<std::collections::VecDeque<(std::path::PathBuf, u64)>>,
    > = std::sync::OnceLock::new();
    RECORDS.get_or_init(|| std::sync::Mutex::new(std::collections::VecDeque::new()))
}

/// Parks how long staging `path` took, for the alignment run that will be
/// handed that path to claim.
pub(crate) fn record_staging_duration(path: &Path, nanos: u64) {
    let Ok(mut records) = staging_durations().lock() else { return };
    // Same path staged twice (the content-addressed hit case) replaces rather
    // than duplicates, so a claim always reads the most recent measurement.
    records.retain(|(p, _)| p != path);
    while records.len() >= STAGING_RECORD_CAPACITY {
        records.pop_front();
    }
    records.push_back((path.to_path_buf(), nanos));
}

/// Claims and REMOVES the staging record for `path`, if this process has one.
///
/// `None` means "this process has no record for that path" — a hand-passed
/// path, a path staged before an eviction, or a path staged by nothing at
/// all. That is genuinely unknown and is reported as `null`, not as zero.
/// Removing on claim is what keeps a one-shot record from being re-attributed
/// to a later, differently-timed run against the same content-addressed path.
pub(crate) fn take_staging_duration(path: &Path) -> Option<u64> {
    let mut records = staging_durations().lock().ok()?;
    let index = records.iter().position(|(p, _)| p == path)?;
    records.remove(index).map(|(_, nanos)| nanos)
}

#[cfg(test)]
pub(crate) fn reset_staging_durations_for_tests() {
    if let Ok(mut records) = staging_durations().lock() {
        records.clear();
    }
}

#[tauri::command]
pub fn fa_stage_audio_raw(request: tauri::ipc::Request<'_>) -> Result<String, String> {
    let staging_started = std::time::Instant::now();
    let headers = request.headers();
    let cache_dir_name = headers
        .get("cache-dir")
        .and_then(|v| v.to_str().ok())
        .ok_or_else(|| "fa_stage_audio_raw: missing or invalid 'cache-dir' header".to_string())?;
    let ext_hint = headers
        .get("ext-hint")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");

    let bytes = match request.body() {
        tauri::ipc::InvokeBody::Raw(data) => data,
        tauri::ipc::InvokeBody::Json(_) => {
            return Err("fa_stage_audio_raw: expected a raw byte body, got JSON".to_string())
        }
    };

    let input_dir = std::env::temp_dir().join(cache_dir_name);
    fs::create_dir_all(&input_dir).map_err(|e| format!("create audio input cache dir: {e}"))?;
    let mut hasher = crate::sha256::Sha256::new();
    hasher.update(bytes);
    let content_key = crate::sha256::hex_digest(&hasher.finish());
    let input_path = input_dir.join(format!("{content_key}.{}", extension_for(ext_hint)));
    if !input_path.exists() {
        fs::write(&input_path, bytes).map_err(|e| format!("write audio: {e}"))?;
    }

    // Measured across the SHA-256 of the whole body plus the write — the two
    // things this command actually costs. Recorded only on success: a failed
    // staging returns `Err` and no alignment run will ever claim a record for
    // a path it was never given.
    record_staging_duration(&input_path, crate::fa::elapsed_nanos(staging_started));
    Ok(input_path.to_string_lossy().to_string())
}

/// Dev-only end-to-end FA entry point (WS1 Task 5 Slice D10): resolves +
/// manifest-verifies the model for `language`, then (WS1 Task 5 Slice D25
/// A1) obtains a 16kHz mono WAV via `fa::ensure_durable_wav` — the durable,
/// LRU-evicted cache under `app_local_data_dir()/fa-audio-cache/` (WS1 Task
/// 5 Slice D24 B1/B2) — rather than transcoding to a throwaway per-call WAV
/// as before, then delegates to the real `fa_align` unmodified.
///
/// `input_path` is a content-addressed file `fa_stage_audio_raw` (above)
/// already staged under `kinetix-fa-dev-inputs` — the frontend calls that
/// command first, with the raw audio bytes as the request body, and passes
/// the returned path here.
///
/// Neither the dev-input cache nor the durable WAV cache is cleaned up at
/// the end of this call (both are deliberately persistent, unlike the old
/// per-call temp directory) — that's the durable cache's whole point: a
/// second `fa_align_dev` call against the same clip should skip transcoding
/// entirely.
///
/// `chunks` (WS1 Task 5 Slice D11) replaces the pre-D11 `segments` param —
/// `src/services/faChunkPlan.ts` builds the ordered `{startSec, endSec,
/// text}` windows this now takes, one per `fa_align` forward pass, instead
/// of a single segment list implicitly aligned against the whole file.
/// Manifest verification above stays exactly once per `fa_align_dev` call
/// (unchanged) — the model-file SHA-256 is independent of, and unaffected
/// by, `fa_align`'s own internal per-chunk `Session` cache (`fa_onnx.rs`'s
/// `CachedSession`, keyed separately on file size+mtime for staleness).
#[tauri::command]
pub async fn fa_align_dev(
    app: tauri::AppHandle,
    state: tauri::State<'_, FaState>,
    model_cache: tauri::State<'_, FaModelCache>,
    input_path: String,
    chunks: Vec<FaChunkInput>,
    language: String,
    on_event: Channel<FaEvent>,
) -> Result<(), FaError> {
    resolve_wav_and_align(app, state, model_cache, input_path, chunks, language, on_event).await
}

/// Shared body behind both `fa_align_dev` (above) and the production,
/// capability-gated `fa_align_production` (`fa_production.rs`,
/// docs/work-in-progress.md §11 item 1): resolves + manifest-verifies the
/// model, obtains a durable 16kHz mono WAV via `fa::ensure_durable_wav` from
/// the already-staged `input_path` (see `fa_stage_audio_raw` above — the
/// caller runs that first and passes its result here), then delegates to
/// the real, unmodified `fa_align`. Extracted as its own function (rather
/// than duplicated) so the production command is provably running the exact
/// same resolve-then-delegate path this dev command has already been
/// live-verified against a real `AppHandle<Wry>` (D25 A1) — one
/// implementation, two thin command wrappers.
pub(crate) async fn resolve_wav_and_align(
    app: tauri::AppHandle,
    state: tauri::State<'_, FaState>,
    model_cache: tauri::State<'_, FaModelCache>,
    input_path: String,
    chunks: Vec<FaChunkInput>,
    language: String,
    on_event: Channel<FaEvent>,
) -> Result<(), FaError> {
    // WS3 fa-perf-foundation — the run clock starts HERE, before the manifest
    // hash and the durable-WAV transcode, so `FaRunTiming::totalMs` covers the
    // two most expensive prefix stages rather than beginning after them.
    let run_started = std::time::Instant::now();

    // SINGLE FLIGHT (WS3 fa-perf-foundation). Claimed BEFORE the ~1.26 GiB
    // manifest hash, before the durable-WAV transcode, and before any model
    // is loaded — a refused duplicate must cost nothing, exactly as
    // `whisper_transcribe` takes its claim before writing a file or spawning
    // a process.
    //
    // Held for the whole call by `_in_flight`, whose `Drop` releases it on
    // EVERY exit: the `?` on `fa_model_path`/`verify_model_manifest`/
    // `ensure_durable_wav_timed`, the `Err(Cancelled)` a cancelled run
    // returns through the tail call, the normal `Ok`, and a panic. There is
    // no explicit release anywhere in this function, and there must not be
    // one.
    //
    // The sink is built BEFORE the claim, mirroring the ordering
    // `whisper.rs` and `model_download::stream_download_verified` establish:
    // a claim must never be visible in the registry with no sink behind it.
    let key = input_path.clone();
    let sink = std::sync::Arc::new(crate::fa::FaSink::new(on_event.clone()));
    let _in_flight = match crate::fa::try_acquire_fa_run(&key, sink.clone()) {
        Some(guard) => guard,
        None => {
            let message = crate::fa::in_flight_refusal(&key);
            // Both an event AND an `Err`: a caller watching only the channel
            // still learns why nothing happened. `sink.send` rather than any
            // retained-terminal-event mechanism — this is not this key's
            // terminal event, it is a statement about a run that is still
            // ALIVE under that key and about to report its own real result.
            sink.send(FaEvent::Error { message: message.clone() });
            return Err(FaError::already_running(message));
        }
    };

    // Claimed (and removed) rather than merely read: this run owns the
    // staging measurement for the path it was handed. `None` when this
    // process never staged that path — reported as unknown, not as zero.
    let staging_nanos = take_staging_duration(Path::new(&input_path));

    let model_path = fa_model_path(&app, &language)?;
    // Probe BEFORE the call: only the state of the memo beforehand
    // distinguishes a map lookup from a full ~1.26 GiB stream hash, and after
    // `verify_model_manifest` returns, both cases look identical.
    let manifest_digest_cache_hit = digest_is_memoized(&model_path);
    let manifest_started = std::time::Instant::now();
    verify_model_manifest(&model_path, &language)?;
    let manifest_verify_nanos = crate::fa::elapsed_nanos(manifest_started);

    let wav_started = std::time::Instant::now();
    let (wav_path, durable_wav_cache_hit) =
        crate::fa::ensure_durable_wav_timed(&app, Path::new(&input_path)).await?;
    let durable_wav_nanos = crate::fa::elapsed_nanos(wav_started);

    let prefix = crate::fa_timing::FaStagePrefix {
        staging_nanos,
        durable_wav_nanos,
        durable_wav_cache_hit,
        manifest_verify_nanos,
        manifest_digest_cache_hit,
    };

    let audio_path = wav_path.to_string_lossy().to_string();
    crate::fa::fa_align_with_prefix(
        app, state, model_cache, audio_path, chunks, language, on_event, prefix, run_started,
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_for_recognizes_common_hints() {
        assert_eq!(extension_for("audio/wav"), "wav");
        assert_eq!(extension_for("mp3"), "mp3");
        assert_eq!(extension_for("audio/mp4"), "m4a");
        assert_eq!(extension_for("something-unknown"), "bin");
    }

    // -- staging-duration hand-off (WS3 fa-perf-foundation) ---------------
    //
    // `staging_durations()` is one process-global table and `cargo test` runs
    // these in parallel threads, so each test below takes this lock for its
    // whole body. Without it, one test's `reset_staging_durations_for_tests`
    // erases another's record mid-flight and the failure looks like a bug in
    // the code under test rather than in the fixture — observed exactly once
    // while writing these. Poison is recovered rather than propagated: a
    // panic in one test must not cascade into failing every sibling.
    static STAGING_TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn staging_test_guard() -> std::sync::MutexGuard<'static, ()> {
        let guard = STAGING_TEST_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        reset_staging_durations_for_tests();
        guard
    }

    //
    // `fa_stage_audio_raw` and `fa_align_production` are two separate IPC
    // commands, so the staging measurement has to survive the gap between
    // them. These prove the hand-off, its bound, and — most importantly —
    // that an absent record reads as UNKNOWN rather than as zero.

    #[test]
    fn a_staged_path_hands_its_duration_to_the_run_that_claims_it() {
        let _guard = staging_test_guard();
        let path = std::path::PathBuf::from("/tmp/kinetix-fa-test/abc.wav");
        record_staging_duration(&path, 4_200_000);
        assert_eq!(take_staging_duration(&path), Some(4_200_000));
    }

    #[test]
    fn a_claim_removes_the_record_so_a_later_run_cannot_reuse_a_stale_measurement() {
        let _guard = staging_test_guard();
        let path = std::path::PathBuf::from("/tmp/kinetix-fa-test/once.wav");
        record_staging_duration(&path, 999);
        assert_eq!(take_staging_duration(&path), Some(999));
        assert_eq!(
            take_staging_duration(&path),
            None,
            "a second run against the same content-addressed path did no staging of its own — it              must report unknown, not inherit the first run's number"
        );
    }

    #[test]
    fn an_unstaged_path_reports_unknown_not_zero() {
        let _guard = staging_test_guard();
        assert_eq!(take_staging_duration(std::path::Path::new("/tmp/never-staged.wav")), None);
    }

    #[test]
    fn restaging_the_same_path_replaces_rather_than_duplicating_its_record() {
        let _guard = staging_test_guard();
        let path = std::path::PathBuf::from("/tmp/kinetix-fa-test/again.wav");
        record_staging_duration(&path, 100);
        record_staging_duration(&path, 200);
        assert_eq!(take_staging_duration(&path), Some(200), "the most recent measurement wins");
        assert_eq!(take_staging_duration(&path), None, "and there is only ever one record per path");
    }

    #[test]
    fn the_record_table_is_bounded_and_evicts_oldest_first() {
        let _guard = staging_test_guard();
        for i in 0..(STAGING_RECORD_CAPACITY + 4) {
            record_staging_duration(&std::path::PathBuf::from(format!("/tmp/kinetix-fa-test/{i}.wav")), i as u64);
        }
        // The four oldest are gone; an evicted record reports unknown.
        for i in 0..4 {
            assert_eq!(
                take_staging_duration(std::path::Path::new(&format!("/tmp/kinetix-fa-test/{i}.wav"))),
                None,
                "record {i} must have been evicted by the cap"
            );
        }
        // The most recent survives with its real value.
        let last = STAGING_RECORD_CAPACITY + 3;
        assert_eq!(
            take_staging_duration(std::path::Path::new(&format!("/tmp/kinetix-fa-test/{last}.wav"))),
            Some(last as u64)
        );
    }

    // -- manifest digest hit/miss probe (WS3 fa-perf-foundation) -----------

    #[test]
    fn digest_probe_distinguishes_a_memo_hit_from_a_cold_full_hash() {
        // Deliberately does NOT call `reset_verified_digest_cache_for_tests`.
        // That memo is process-global and two sibling tests here already
        // reset it; a third resetter clobbers them mid-flight under parallel
        // execution. MEASURED: adding a reset here turned
        // `digest_for_sidecar_computes_and_caches_on_a_cold_call` and
        // `digest_memo_caches_by_identity_and_resets_cleanly` red on one run
        // in six. A UUID-unique path is cold by construction and needs no
        // reset to prove it.
        let dir = std::env::temp_dir().join(format!("kinetix-fa-digest-probe-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        fs::write(&path, b"not a real model, but a real file identity").unwrap();

        assert!(
            !digest_is_memoized(&path),
            "cold: the next verify would pay the full stream hash, so the probe must say MISS"
        );
        // `digest_for_sidecar` populates the SAME memo `verify_model_manifest`
        // reads — that shared cache is the whole reason this probe works
        // without touching the verification function's internals.
        digest_for_sidecar(&path).unwrap();
        assert!(digest_is_memoized(&path), "warm: the next verify is a map lookup, so the probe must say HIT");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn digest_probe_reports_miss_for_a_path_that_does_not_exist() {
        // Must not panic, and must not claim a hit it cannot have.
        assert!(!digest_is_memoized(std::path::Path::new("/definitely/not/here/model.onnx")));
    }

    #[test]
    fn manifest_sha256_for_known_language_matches_committed_manifest() {
        let hash = manifest_sha256_for("en").expect("en must be in the manifest");
        assert_eq!(hash.len(), 64, "sha256 hex digest must be 64 chars");
    }

    /// WS2 T4.8: `digest_for_sidecar` must reuse whatever `verify_model_
    /// manifest` already cached for this exact file identity, not re-hash.
    /// Proven the same way `model_download.rs`'s finalize test proves it: seed
    /// the cache with a digest that is NOT the file's real sha256 (a real
    /// re-hash would never produce it), then confirm `digest_for_sidecar`
    /// returns exactly that value — a cache hit, not a second read.
    #[test]
    fn digest_for_sidecar_reuses_verify_model_manifests_cache_not_a_re_hash() {
        reset_verified_digest_cache_for_tests();
        let dir = std::env::temp_dir().join(format!("fa-dev-digest-sidecar-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"whatever bytes are actually here").unwrap();

        let meta = std::fs::metadata(&path).unwrap();
        let identity: ModelIdentity = (path.clone(), meta.len(), meta.modified().ok());
        let planted = "not-the-real-sha256-just-a-marker".to_string();
        verified_digest_cache().lock().unwrap().insert(identity, planted.clone());

        let got = digest_for_sidecar(&path).expect("cache hit must not touch the filesystem for a hash");
        assert_eq!(got, planted, "must return the CACHED digest, proving no independent re-hash ran");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The cold path — no prior cache entry — still produces the real digest
    /// and populates the cache for next time, same as `verify_model_manifest`
    /// itself does.
    #[test]
    fn digest_for_sidecar_computes_and_caches_on_a_cold_call() {
        reset_verified_digest_cache_for_tests();
        let dir = std::env::temp_dir().join(format!("fa-dev-digest-sidecar-cold-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        let content = b"some real content to hash";
        std::fs::write(&path, content).unwrap();

        let expected = crate::sha256::hash_file(&path).unwrap();
        let got = digest_for_sidecar(&path).unwrap();
        assert_eq!(got, expected);

        let meta = std::fs::metadata(&path).unwrap();
        let identity: ModelIdentity = (path.clone(), meta.len(), meta.modified().ok());
        assert_eq!(
            verified_digest_cache().lock().unwrap().get(&identity),
            Some(&expected),
            "a cold call must populate the cache for the next caller"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// WS1 Session G — the REAL fail-clean budget measurement, against a real
    /// ~1.26 GiB `model.onnx`. Env-gated (`FA_FAILCLEAN_BENCH=1`) and
    /// `#[ignore]`d for the same reason `tests/fa_durable_wav_live.rs` is: it
    /// needs a real model on disk plus ~1.3 GiB of scratch space, and it is a
    /// measurement, not a regression assertion. Run:
    ///   FA_FAILCLEAN_BENCH=1 cargo test --features fa-inference \
    ///     fail_clean_budget_real_model -- --ignored --nocapture
    /// (and again with `--release` for the release column).
    #[test]
    #[ignore]
    fn fail_clean_budget_real_model() {
        if std::env::var("FA_FAILCLEAN_BENCH").ok().as_deref() != Some("1") {
            eprintln!("SKIP fail_clean_budget_real_model: set FA_FAILCLEAN_BENCH=1");
            return;
        }
        let profile = if cfg!(debug_assertions) { "DEBUG" } else { "RELEASE" };
        let home = std::env::var("HOME").expect("HOME");
        let real = std::path::PathBuf::from(&home)
            .join("Library/Application Support/com.kinetix.pro-studio/fa-models/en/model.onnx");
        assert!(real.exists(), "real en model not present at {}", real.display());

        let dir = std::env::temp_dir().join(format!("fa-g-bench-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let ms = |d: std::time::Duration| format!("{:.3} ms", d.as_secs_f64() * 1000.0);

        println!("\n=== FAIL-CLEAN BUDGET — {profile} build, production fn verify_model_manifest ===");

        // (1) ABSENT MODEL
        reset_verified_digest_cache_for_tests();
        let absent = dir.join("nope.onnx");
        let t = std::time::Instant::now();
        let e = verify_model_manifest(&absent, "en").unwrap_err();
        println!("absent model                     : {} [{:?}]", ms(t.elapsed()), e.kind);

        // (2) TRUNCATED / WRONG-SIZE MODEL (tier A — size precheck)
        reset_verified_digest_cache_for_tests();
        let trunc = dir.join("truncated.onnx");
        std::fs::write(&trunc, vec![0u8; 64 * 1024 * 1024]).unwrap();
        let t = std::time::Instant::now();
        let e = verify_model_manifest(&trunc, "en").unwrap_err();
        println!("corrupt: truncated (64 MiB)      : {} [{:?}]", ms(t.elapsed()), e.kind);
        let t = std::time::Instant::now();
        let _ = verify_model_manifest(&trunc, "en");
        println!("corrupt: truncated, 2nd call     : {}", ms(t.elapsed()));
        let _ = std::fs::remove_file(&trunc);

        // (3) SAME-SIZE BYTE-FLIP (tier B — full size, one byte changed)
        reset_verified_digest_cache_for_tests();
        let flipped = dir.join("flipped.onnx");
        std::fs::copy(&real, &flipped).unwrap();
        {
            use std::io::{Seek, SeekFrom, Write};
            let mut f = std::fs::OpenOptions::new().write(true).open(&flipped).unwrap();
            f.seek(SeekFrom::Start(600_000_000)).unwrap();
            f.write_all(&[0xFF]).unwrap();
        }
        let t = std::time::Instant::now();
        let e = verify_model_manifest(&flipped, "en").unwrap_err();
        println!("corrupt: byte-flip, 1st (cold)   : {} [{:?}]", ms(t.elapsed()), e.kind);
        let t = std::time::Instant::now();
        let _ = verify_model_manifest(&flipped, "en");
        println!("corrupt: byte-flip, 2nd (memo)   : {}", ms(t.elapsed()));
        let _ = std::fs::remove_file(&flipped);

        // (4) HEALTHY MODEL (tier C)
        reset_verified_digest_cache_for_tests();
        let t = std::time::Instant::now();
        verify_model_manifest(&real, "en").expect("real model must verify");
        println!("healthy model, 1st (cold)        : {}", ms(t.elapsed()));
        let t = std::time::Instant::now();
        verify_model_manifest(&real, "en").expect("real model must verify");
        println!("healthy model, 2nd (memo)        : {}", ms(t.elapsed()));
        let t = std::time::Instant::now();
        verify_model_manifest(&real, "en").expect("real model must verify");
        println!("healthy model, 3rd (memo)        : {}", ms(t.elapsed()));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn manifest_sha256_for_unknown_language_is_none() {
        assert!(manifest_sha256_for("zz").is_none());
    }

    #[test]
    fn verify_model_manifest_rejects_a_corrupted_file() {
        let dir = std::env::temp_dir().join(format!("fa-dev-manifest-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"not the real model").unwrap();

        let err = verify_model_manifest(&path, "en").unwrap_err();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        // WS1 Session G: an 18-byte file is now rejected by the SIZE
        // precheck before any hashing, so the message names the size fault
        // rather than the digest one. Still ModelHashMismatch, still
        // fail-clean, still the same refusal — just reached ~4 orders of
        // magnitude sooner.
        assert!(
            err.message.contains("truncated") && err.message.contains("18 bytes"),
            "expected the size-precheck message, got: {}",
            err.message
        );
    }

    // -- WS1 Session G: fail-clean budget -----------------------------------

    /// Tier A: a size-detectable fault must be refused without hashing. This
    /// asserts the mechanism rather than a wall-clock number (which would be
    /// machine-dependent and flaky in CI): the file is a size the real model
    /// never is, and the error names the size fault, which is only reachable
    /// on the pre-hash path.
    #[test]
    fn size_precheck_rejects_a_truncated_model_without_hashing() {
        let dir = std::env::temp_dir().join(format!("fa-g-size-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        // Deliberately large enough that hashing it would be measurable, and
        // still nowhere near the manifest's 1_262_512_711 for "en".
        std::fs::write(&path, vec![0u8; 4 * 1024 * 1024]).unwrap();

        let started = std::time::Instant::now();
        let err = verify_model_manifest(&path, "en").unwrap_err();
        let elapsed = started.elapsed();
        let _ = std::fs::remove_dir_all(&dir);

        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        assert!(err.message.contains("wrong or truncated file"), "got: {}", err.message);
        assert!(err.message.contains("1262512711"), "must name the expected size; got: {}", err.message);
        // Generous by 2+ orders of magnitude vs. the stated 50ms tier-A
        // budget — this is a "did we skip the hash" assertion, not a
        // benchmark, and must not flake on a loaded machine.
        assert!(elapsed.as_millis() < 2_000, "size precheck took {elapsed:?}");
    }

    #[test]
    fn manifest_byte_size_is_recorded_for_every_supported_language() {
        // The precheck is only as good as the manifest data behind it: if a
        // language had no byteSize, that language would silently lose tier A.
        for lang in ["en", "es", "fr", "de", "pt"] {
            assert!(
                manifest_byte_size_for(lang).is_some_and(|n| n > 1_000_000_000),
                "manifest byteSize missing/implausible for {lang}"
            );
        }
        assert!(manifest_byte_size_for("zz").is_none());
    }

    /// Tier B/C: the full-file hash is paid at most ONCE per file identity
    /// per process. Uses a language whose manifest byteSize is absent
    /// ("zz" has no entry at all, so instead we verify the memo directly)
    /// — here the memo is observed through its own public-in-crate reset.
    #[test]
    fn digest_memo_caches_by_identity_and_resets_cleanly() {
        let dir = std::env::temp_dir().join(format!("fa-g-memo-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, vec![7u8; 2 * 1024 * 1024]).unwrap();

        reset_verified_digest_cache_for_tests();
        let meta = std::fs::metadata(&path).unwrap();
        let identity: ModelIdentity = (path.clone(), meta.len(), meta.modified().ok());

        // Cold: nothing memoized yet.
        assert!(verified_digest_cache().lock().unwrap().get(&identity).is_none());

        // A verify against a language WITH a byteSize would stop at the size
        // precheck and never populate the memo — which is itself the tier-A
        // behaviour. Drive the hash path directly to populate it, exactly as
        // a correctly-sized model would.
        let digest = crate::sha256::hash_file(&path).unwrap();
        verified_digest_cache().lock().unwrap().insert(identity.clone(), digest.clone());
        assert_eq!(verified_digest_cache().lock().unwrap().get(&identity), Some(&digest));

        // A changed size is a DIFFERENT identity — never a stale hit.
        let other: ModelIdentity = (path.clone(), meta.len() + 1, meta.modified().ok());
        assert!(verified_digest_cache().lock().unwrap().get(&other).is_none());

        reset_verified_digest_cache_for_tests();
        assert!(verified_digest_cache().lock().unwrap().get(&identity).is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_model_manifest_rejects_unknown_language() {
        let dir = std::env::temp_dir().join(format!("fa-dev-manifest-test2-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"irrelevant").unwrap();

        let err = verify_model_manifest(&path, "zz").unwrap_err();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        assert!(err.message.contains("no manifest entry"));
    }
}
