// ---------------------------------------------------------------------------
// Dev-only forced-alignment invocation path (WS1 Task 5 Slice D10).
//
// NOT reachable from any UI control — no button, no menu item, no Settings
// toggle references this command. The only caller is `src/App.tsx`'s
// DEV-gated `window.__faDevAlign` global (mirrors `__transcriptInspector`'s
// own precedent: a `import.meta.env.DEV`-gated `useEffect` exposing a
// console-invokable function, never wired into any component's render
// output), invoked from the devtools console.
//
// Exists because `fa_align` (`fa.rs`) takes a filesystem path to an
// already-16kHz-mono-WAV file — by design (its own doc comment: "reuses
// whatever the caller already has on disk"), it does not itself transcode
// anything. In production, no caller currently produces a DURABLE WAV at a
// path `fa_align` could consume: `whisper.rs::transcode_to_wav` produces one
// but `whisper_transcribe` deletes it (`fs::remove_dir_all`) the moment
// whisper-cli exits — confirmed by reading that function before writing this
// one. This command closes that gap for the dev path only, by preparing its
// own throwaway WAV (the SAME `transcode_to_wav` helper, same
// temp-dir-then-cleanup lifecycle `whisper_transcribe` already uses) and
// then delegating to the REAL, unmodified `fa_align` — so what this slice
// actually exercises is production `fa_align` itself, not a reimplementation
// of it.
// ---------------------------------------------------------------------------

use crate::fa::{fa_align, fa_model_path, FaError, FaErrorKind, FaEvent, FaSegmentInput, FaState};
use base64::{engine::general_purpose::STANDARD, Engine};
use std::fs;
use std::path::Path;
use tauri::ipc::Channel;
use uuid::Uuid;

/// Embedded verbatim (WS1 Task 5 Slice D2's `fa-onnx-manifest.json`,
/// generated by `scripts/export-fa-onnx.py`) — same `include_str!`
/// convention `fa_onnx.rs::vocab_json_for` already uses for the per-language
/// vocab fixtures. The manifest's own `_provenance.note` says "Consumed by
/// Step T (deferred)" — Step T (the on-demand downloader) is still deferred;
/// this is a DIFFERENT consumer (a manual pre-use integrity check for a
/// model an operator placed by hand per the R-D manual-placement fallback),
/// not Step T itself.
const FA_ONNX_MANIFEST_JSON: &str = include_str!("../../scripts/fixtures/fa-onnx-manifest.json");

fn manifest_sha256_for(language: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(FA_ONNX_MANIFEST_JSON).ok()?;
    v["models"][language]["sha256"].as_str().map(|s| s.to_string())
}

/// Hashes `path` and compares against the committed manifest's recorded
/// SHA-256 for `language`. Never panics — a missing manifest entry, an I/O
/// failure, and a genuine hash mismatch are all reported as a typed
/// `FaError` (`ModelHashMismatch`), not a crash. The mismatch case is the
/// real integrity check this function exists for: a `model.onnx` placed by
/// hand could be truncated, corrupted, or simply the wrong file.
fn verify_model_manifest(path: &Path, language: &str) -> Result<(), FaError> {
    let expected = manifest_sha256_for(language).ok_or_else(|| FaError {
        kind: FaErrorKind::ModelHashMismatch,
        message: format!("no manifest entry for language \"{language}\" in fa-onnx-manifest.json"),
    })?;
    let actual = crate::sha256::hash_file(path).map_err(|e| FaError {
        kind: FaErrorKind::ModelHashMismatch,
        message: format!("failed to hash model at {}: {e}", path.display()),
    })?;
    if actual != expected {
        return Err(FaError {
            kind: FaErrorKind::ModelHashMismatch,
            message: format!(
                "model at {} does not match the committed manifest for \"{language}\" — expected \
                 sha256 {expected}, got {actual}. Re-download/re-export the model; do not trust a \
                 mismatched file.",
                path.display()
            ),
        });
    }
    Ok(())
}

/// A reasonable temp filename extension from the caller-supplied hint.
/// `whisper.rs::transcode_to_wav` (ffmpeg) probes container format from the
/// file's actual content, not its extension, so an unrecognized hint still
/// works correctly — this only affects the temp filename's cosmetics.
fn extension_for(hint: &str) -> &'static str {
    match hint {
        "wav" | "audio/wav" | "audio/wave" | "audio/x-wav" => "wav",
        "mp3" | "audio/mpeg" | "audio/mp3" => "mp3",
        "ogg" | "audio/ogg" => "ogg",
        "flac" | "audio/flac" => "flac",
        "m4a" | "audio/mp4" | "audio/x-m4a" | "audio/aac" => "m4a",
        "aiff" | "audio/aiff" => "aiff",
        "webm" | "audio/webm" => "webm",
        _ => "bin",
    }
}

fn dev_error(message: impl Into<String>) -> FaError {
    FaError { kind: FaErrorKind::InferenceFailed, message: message.into() }
}

/// Dev-only end-to-end FA entry point (WS1 Task 5 Slice D10): resolves +
/// manifest-verifies the model for `language`, decodes `audio_b64`,
/// transcodes it to a throwaway 16kHz mono WAV (mirroring
/// `whisper_transcribe`'s own lifecycle), then delegates to the real
/// `fa_align` unmodified. Always cleans up its own temp directory, success
/// or failure alike.
#[tauri::command]
pub async fn fa_align_dev(
    app: tauri::AppHandle,
    state: tauri::State<'_, FaState>,
    audio_b64: String,
    audio_ext_hint: String,
    segments: Vec<FaSegmentInput>,
    language: String,
    on_event: Channel<FaEvent>,
) -> Result<(), FaError> {
    let model_path = fa_model_path(&app, &language)?;
    verify_model_manifest(&model_path, &language)?;

    let audio_bytes = STANDARD
        .decode(&audio_b64)
        .map_err(|e| dev_error(format!("base64 decode failed: {e}")))?;

    let tmp_id = Uuid::new_v4().to_string();
    let tmp_dir = std::env::temp_dir().join(format!("kinetix-fa-dev-{}", tmp_id));
    fs::create_dir_all(&tmp_dir).map_err(|e| dev_error(format!("create temp dir: {e}")))?;

    let input_path = tmp_dir.join(format!("input.{}", extension_for(&audio_ext_hint)));
    if let Err(e) = fs::write(&input_path, &audio_bytes) {
        let _ = fs::remove_dir_all(&tmp_dir);
        return Err(dev_error(format!("write audio: {e}")));
    }

    let wav_path = tmp_dir.join("input_16k.wav");
    if let Err(e) = crate::whisper::transcode_to_wav(&app, &input_path, &wav_path).await {
        let _ = fs::remove_dir_all(&tmp_dir);
        return Err(dev_error(format!("transcode to WAV: {e}")));
    }

    let audio_path = wav_path.to_string_lossy().to_string();
    let result = fa_align(app, state, audio_path, segments, language, on_event).await;
    let _ = fs::remove_dir_all(&tmp_dir);
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_for_recognizes_common_hints() {
        assert_eq!(extension_for("audio/wav"), "wav");
        assert_eq!(extension_for("mp3"), "mp3");
        assert_eq!(extension_for("audio/mp4"), "m4a");
        assert_eq!(extension_for("something-unknown"), "bin");
    }

    #[test]
    fn manifest_sha256_for_known_language_matches_committed_manifest() {
        let hash = manifest_sha256_for("en").expect("en must be in the manifest");
        assert_eq!(hash.len(), 64, "sha256 hex digest must be 64 chars");
    }

    #[test]
    fn manifest_sha256_for_unknown_language_is_none() {
        assert!(manifest_sha256_for("zz").is_none());
    }

    #[test]
    fn verify_model_manifest_rejects_a_corrupted_file() {
        let dir = std::env::temp_dir().join(format!("fa-dev-manifest-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"not the real model").unwrap();

        let err = verify_model_manifest(&path, "en").unwrap_err();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        assert!(err.message.contains("does not match"));
    }

    #[test]
    fn verify_model_manifest_rejects_unknown_language() {
        let dir = std::env::temp_dir().join(format!("fa-dev-manifest-test2-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"irrelevant").unwrap();

        let err = verify_model_manifest(&path, "zz").unwrap_err();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        assert!(err.message.contains("no manifest entry"));
    }
}
