// ---------------------------------------------------------------------------
// Dev-only forced-alignment invocation path (WS1 Task 5 Slice D10).
//
// NOT reachable from any UI control — no button, no menu item, no Settings
// toggle references this command. The only caller is `src/App.tsx`'s
// DEV-gated `window.__faDevAlign` global (mirrors `__transcriptInspector`'s
// own precedent: a `import.meta.env.DEV`-gated `useEffect` exposing a
// console-invokable function, never wired into any component's render
// output), invoked from the devtools console.
//
// Exists because `fa_align` (`fa.rs`) takes a filesystem path to an
// already-16kHz-mono-WAV file — by design (its own doc comment: "reuses
// whatever the caller already has on disk"), it does not itself transcode
// anything. In production, no caller currently produces a DURABLE WAV at a
// path `fa_align` could consume: `whisper.rs::transcode_to_wav` produces one
// but `whisper_transcribe` deletes it (`fs::remove_dir_all`) the moment
// whisper-cli exits — confirmed by reading that function before writing this
// one. This command closes that gap for the dev path by obtaining a durable
// WAV via `fa::ensure_durable_wav` (WS1 Task 5 Slice D25 A1 — previously a
// throwaway per-call WAV via `transcode_to_wav` directly, see `fa_align_dev`'s
// own doc comment for why that changed) and then delegating to the REAL,
// unmodified `fa_align` — so what this slice actually exercises is production
// `fa_align` (and, as of D25, production `ensure_durable_wav`) itself, not a
// reimplementation of either.
// ---------------------------------------------------------------------------

use crate::fa::{fa_align, fa_model_path, FaChunkInput, FaError, FaErrorKind, FaEvent, FaModelCache, FaState};
use base64::{engine::general_purpose::STANDARD, Engine};
use std::fs;
use std::path::Path;
use tauri::ipc::Channel;

/// Embedded verbatim (WS1 Task 5 Slice D2's `fa-onnx-manifest.json`,
/// generated by `scripts/export-fa-onnx.py`) — same `include_str!`
/// convention `fa_onnx.rs::vocab_json_for` already uses for the per-language
/// vocab fixtures. The manifest's own `_provenance.note` says "Consumed by
/// Step T (deferred)" — Step T (the on-demand downloader) is still deferred;
/// this is a DIFFERENT consumer (a manual pre-use integrity check for a
/// model an operator placed by hand per the R-D manual-placement fallback),
/// not Step T itself.
const FA_ONNX_MANIFEST_JSON: &str = include_str!("../../scripts/fixtures/fa-onnx-manifest.json");

fn manifest_sha256_for(language: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(FA_ONNX_MANIFEST_JSON).ok()?;
    v["models"][language]["sha256"].as_str().map(|s| s.to_string())
}

/// Hashes `path` and compares against the committed manifest's recorded
/// SHA-256 for `language`. Never panics — a missing manifest entry, an I/O
/// failure, and a genuine hash mismatch are all reported as a typed
/// `FaError` (`ModelHashMismatch`), not a crash. The mismatch case is the
/// real integrity check this function exists for: a `model.onnx` placed by
/// hand could be truncated, corrupted, or simply the wrong file.
fn verify_model_manifest(path: &Path, language: &str) -> Result<(), FaError> {
    let expected = manifest_sha256_for(language).ok_or_else(|| FaError {
        kind: FaErrorKind::ModelHashMismatch,
        message: format!("no manifest entry for language \"{language}\" in fa-onnx-manifest.json"),
    })?;
    let actual = crate::sha256::hash_file(path).map_err(|e| FaError {
        kind: FaErrorKind::ModelHashMismatch,
        message: format!("failed to hash model at {}: {e}", path.display()),
    })?;
    if actual != expected {
        return Err(FaError {
            kind: FaErrorKind::ModelHashMismatch,
            message: format!(
                "model at {} does not match the committed manifest for \"{language}\" — expected \
                 sha256 {expected}, got {actual}. Re-download/re-export the model; do not trust a \
                 mismatched file.",
                path.display()
            ),
        });
    }
    Ok(())
}

/// A reasonable temp filename extension from the caller-supplied hint.
/// `whisper.rs::transcode_to_wav` (ffmpeg) probes container format from the
/// file's actual content, not its extension, so an unrecognized hint still
/// works correctly — this only affects the temp filename's cosmetics.
fn extension_for(hint: &str) -> &'static str {
    match hint {
        "wav" | "audio/wav" | "audio/wave" | "audio/x-wav" => "wav",
        "mp3" | "audio/mpeg" | "audio/mp3" => "mp3",
        "ogg" | "audio/ogg" => "ogg",
        "flac" | "audio/flac" => "flac",
        "m4a" | "audio/mp4" | "audio/x-m4a" | "audio/aac" => "m4a",
        "aiff" | "audio/aiff" => "aiff",
        "webm" | "audio/webm" => "webm",
        _ => "bin",
    }
}

fn dev_error(message: impl Into<String>) -> FaError {
    FaError { kind: FaErrorKind::InferenceFailed, message: message.into() }
}

/// Dev-only end-to-end FA entry point (WS1 Task 5 Slice D10): resolves +
/// manifest-verifies the model for `language`, decodes `audio_b64`, then
/// (WS1 Task 5 Slice D25 A1) obtains a 16kHz mono WAV via
/// `fa::ensure_durable_wav` — the durable, LRU-evicted cache under
/// `app_local_data_dir()/fa-audio-cache/` (WS1 Task 5 Slice D24 B1/B2) —
/// rather than transcoding to a throwaway per-call WAV as before, then
/// delegates to the real `fa_align` unmodified.
///
/// The decoded audio bytes are also written to a content-addressed (SHA-256
/// of the bytes), NOT per-call/uuid'd, path under a stable temp directory
/// (`kinetix-fa-dev-inputs`): `ensure_durable_wav`'s cache key is the SOURCE
/// file's own identity (name|size|mtime — `fa.rs::source_identity_key`), so
/// a fresh uuid'd temp file on every call would give every invocation of the
/// SAME clip a fresh mtime and defeat the durable cache before it ever got a
/// chance to hit. Content-addressing means two calls with byte-identical
/// decoded audio resolve to the same input path, which is left untouched
/// (mtime preserved, not rewritten) if it already exists — so its identity,
/// and therefore the durable WAV cache entry `ensure_durable_wav` resolves
/// it to, is stable across repeated dev invocations of the same clip.
///
/// Neither the dev-input cache nor the durable WAV cache is cleaned up at
/// the end of this call (both are deliberately persistent, unlike the old
/// per-call temp directory) — that's the durable cache's whole point: a
/// second `fa_align_dev` call against the same clip should skip transcoding
/// entirely.
///
/// `chunks` (WS1 Task 5 Slice D11) replaces the pre-D11 `segments` param —
/// `src/services/faChunkPlan.ts` builds the ordered `{startSec, endSec,
/// text}` windows this now takes, one per `fa_align` forward pass, instead
/// of a single segment list implicitly aligned against the whole file.
/// Manifest verification above stays exactly once per `fa_align_dev` call
/// (unchanged) — the model-file SHA-256 is independent of, and unaffected
/// by, `fa_align`'s own internal per-chunk `Session` cache (`fa_onnx.rs`'s
/// `CachedSession`, keyed separately on file size+mtime for staleness).
#[tauri::command]
pub async fn fa_align_dev(
    app: tauri::AppHandle,
    state: tauri::State<'_, FaState>,
    model_cache: tauri::State<'_, FaModelCache>,
    audio_b64: String,
    audio_ext_hint: String,
    chunks: Vec<FaChunkInput>,
    language: String,
    on_event: Channel<FaEvent>,
) -> Result<(), FaError> {
    let model_path = fa_model_path(&app, &language)?;
    verify_model_manifest(&model_path, &language)?;

    let audio_bytes = STANDARD
        .decode(&audio_b64)
        .map_err(|e| dev_error(format!("base64 decode failed: {e}")))?;

    let input_dir = std::env::temp_dir().join("kinetix-fa-dev-inputs");
    fs::create_dir_all(&input_dir).map_err(|e| dev_error(format!("create dev input cache dir: {e}")))?;
    let mut hasher = crate::sha256::Sha256::new();
    hasher.update(&audio_bytes);
    let content_key = crate::sha256::hex_digest(&hasher.finish());
    let input_path = input_dir.join(format!("{content_key}.{}", extension_for(&audio_ext_hint)));
    if !input_path.exists() {
        fs::write(&input_path, &audio_bytes).map_err(|e| dev_error(format!("write audio: {e}")))?;
    }

    let wav_path = crate::fa::ensure_durable_wav(&app, &input_path).await?;

    let audio_path = wav_path.to_string_lossy().to_string();
    fa_align(app, state, model_cache, audio_path, chunks, language, on_event).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_for_recognizes_common_hints() {
        assert_eq!(extension_for("audio/wav"), "wav");
        assert_eq!(extension_for("mp3"), "mp3");
        assert_eq!(extension_for("audio/mp4"), "m4a");
        assert_eq!(extension_for("something-unknown"), "bin");
    }

    #[test]
    fn manifest_sha256_for_known_language_matches_committed_manifest() {
        let hash = manifest_sha256_for("en").expect("en must be in the manifest");
        assert_eq!(hash.len(), 64, "sha256 hex digest must be 64 chars");
    }

    #[test]
    fn manifest_sha256_for_unknown_language_is_none() {
        assert!(manifest_sha256_for("zz").is_none());
    }

    #[test]
    fn verify_model_manifest_rejects_a_corrupted_file() {
        let dir = std::env::temp_dir().join(format!("fa-dev-manifest-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"not the real model").unwrap();

        let err = verify_model_manifest(&path, "en").unwrap_err();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        assert!(err.message.contains("does not match"));
    }

    #[test]
    fn verify_model_manifest_rejects_unknown_language() {
        let dir = std::env::temp_dir().join(format!("fa-dev-manifest-test2-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.onnx");
        std::fs::write(&path, b"irrelevant").unwrap();

        let err = verify_model_manifest(&path, "zz").unwrap_err();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(err.kind, FaErrorKind::ModelHashMismatch);
        assert!(err.message.contains("no manifest entry"));
    }
}
